activity.paramsFormulas = {
  -- event
  ['onStart'] = {},
  ['onClick'] = {},
  ['onClickEnd'] = {},
  ['onClickMove'] = {'value', 'value'},
  ['onFun'] = {'func'},
  ['onCollisionStart'] = {},
  ['onCollisionEnd'] = {},
  ['onBack'] = {},
  ['onHide'] = {},
  ['onView'] = {},

  -- data
  ['setVar'] = {'variable', 'value'},
  ['updVar'] = {'variable', 'value'},
  ['setShowText'] = {'variable', 'font', 'align', 'value', 'value', 'value'},
  ['setHideText'] = {'variable'},
  ['setPosText'] = {'variable', 'value', 'value'},
  ['setPosXText'] = {'variable', 'value'},
  ['setPosYText'] = {'variable', 'value'},
  ['setRotationText'] = {'variable', 'value'},
  ['setAlphaText'] = {'variable', 'value'},
  ['setColorText'] = {'variable', 'color'},
  ['setRGBColorText'] = {'variable', 'value', 'value', 'value'},
  ['setHEXColorText'] = {'variable', 'value'},
  ['updColorText'] = {'variable', 'value'},
  ['updRColorText'] = {'variable', 'value'},
  ['updGColorText'] = {'variable', 'value'},
  ['updBColorText'] = {'variable', 'value'},
  ['setFrontText'] = {'variable'},
  ['setBackText'] = {'variable'},
  ['readVar'] = {'variable'},
  ['writeVar'] = {'variable'},
  ['updTable'] = {'tabl', 'value'},
  ['setTable'] = {'tabl', 'value', 'value'},
  ['setTable2'] = {'tabl', 'value', 'value', 'value'},
  ['setTable3'] = {'tabl', 'value', 'value', 'value', 'value'},
  ['setTable4'] = {'tabl', 'value', 'value', 'value', 'value', 'value'},
  ['removeTable'] = {'tabl', 'value'},
  ['removeTable2'] = {'tabl', 'value', 'value'},
  ['removeTable3'] = {'tabl', 'value', 'value', 'value'},
  ['removeTable4'] = {'tabl', 'value', 'value', 'value', 'value'},

  -- object
  ['setPos'] = {'value', 'value'},
  ['setX'] = {'value'},
  ['setY'] = {'value'},
  ['setSize'] = {'value'},
  ['setWidth'] = {'value'},
  ['setHeight'] = {'value'},
  ['updX'] = {'value'},
  ['updY'] = {'value'},
  ['updSize'] = {'value'},
  ['updWidth'] = {'value'},
  ['updHeight'] = {'value'},
  ['setHide'] = {},
  ['setView'] = {},
  ['setRotation'] = {'value'},
  ['setAlpha'] = {'value'},
  ['setTag'] = {'tag'},
  ['setFront'] = {},
  ['setBack'] = {},
  ['setNameTexture'] = {'texture'},
  ['setIndexTexture'] = {'value'},
  ['setLinkTexture'] = {'value'},
  ['resetSize'] = {},

  -- copy
  ['setCopy'] = {'setcopy'},
  ['removeCopy'] = {'copy'},
  ['setPosCopy'] = {'copy', 'value', 'value'},

  -- control
  ['fun'] = {'func'},
  ['funParams'] = {'func', 'tabl'},
  ['useTag'] = {'tag'},
  ['useTagEnd'] = {},
  ['if'] = {'value'},
  ['ifElse'] = {'value'},
  ['else'] = {},
  ['ifEnd'] = {},
  ['ifElseEnd'] = {},
  ['for'] = {'value'},
  ['forEnd'] = {},
  ['enterFrame'] = {},
  ['enterFrameEnd'] = {},
  ['timer'] = {'value', 'value'},
  ['groupCreate'] = {'scene'},
  ['groupView'] = {'scene'},
  ['setColorBackground'] = {'color'},
  ['setRGBColorBackground'] = {'value', 'value', 'value'},
  ['setHEXColorBackground'] = {'value'},
  ['fileLine'] = {'variable', 'value', 'basedir'},
  ['fileLineEnd'] = {},
  ['fileRead'] = {'variable', 'value', 'basedir'},
  ['fileWrite'] = {'value', 'value', 'basedir'},
  ['fileUpdate'] = {'value', 'value', 'basedir'},
  ['fileMove'] = {'value', 'basedir', 'value', 'basedir'},
  ['fileCopy'] = {'value', 'basedir', 'value', 'basedir'},
  ['fileRemove'] = {'value', 'basedir'},
  ['onMultitouch'] = {},
  ['offMultitouch'] = {},
  ['closeApp'] = {},
  ['commentYourself'] = {'text'},

  -- controlother
  ['inputText'] = {'value', 'variable'},
  ['createTextField'] = {'field', 'value','color', 'value', 'bgfield', 'font'},
  ['createTextBox'] = {'field', 'value','color', 'value', 'bgfield', 'font'},
  ['removeTextField'] = {'field'},
  ['getTextField'] = {'field', 'variable'},
  ['setTextField'] = {'field', 'value'},
  ['getOldTextField'] = {'field', 'variable'},
  ['setPosField'] = {'field', 'value', 'value'},
  ['setSizeField'] = {'field', 'value', 'value'},
  ['setHideField'] = {'field'},
  ['setViewField'] = {'field'},
  ['setInputTypeField'] = {'field', 'typefield'},
  ['setEditField'] = {'field', 'editfield'},
  ['closeKeyboard'] = {},

  -- physics
  ['setBody'] = {'body', 'value', 'value', 'value'},
  ['removeBody'] = {},
  ['setGravity'] = {'value'},
  ['setHitboxMesh'] = {'value'},
  ['setHitboxBox'] = {'editphys'},
  ['setHitboxCircle'] = {'value'},
  ['setNewBody'] = {'body'},
  ['setLinearVelocity'] = {'value', 'value'},
  ['setLinearVelocityX'] = {'value'},
  ['setLinearVelocityY'] = {'value'},
  ['setSensor'] = {},
  ['setNotSensor'] = {},
  ['setFixedRotation'] = {},
  ['setNotFixedRotation'] = {},
  ['setWorldGravity'] = {'value', 'value'},
  ['setVisiblePhysics'] = {},
  ['setNotVisiblePhysics'] = {},
  ['setBullet'] = {},
  ['setNotBullet'] = {},
  ['setAwake'] = {},
  ['setAngularVelocity'] = {'value'},
  ['setAngularDamping'] = {'value'},
  ['setLinearDamping'] = {'value'},
  ['setForce'] = {'value', 'value'},
  ['setLinearImpulse'] = {'value', 'value'},
  ['setTorque'] = {'value'},
  ['setAngularImpulse'] = {'value'},
  ['setPowerPhysics'] = {'powerphys'},
  ['startPhysics'] = {},
  ['stopPhysics'] = {},

  -- physicscopy
  ['setGravityCopy'] = {'copy', 'value'},
  ['setSensorCopy'] = {'copy', 'sensor'},
  ['setPhyRotationCopy'] = {'copy', 'phyrotation'},

  -- network
  ['openUrl'] = {'value'},
  ['setGet'] = {'value', 'variable'},
  ['setPost'] = {'value', 'value', 'variable', 'tabl'}
}

activity.typeFormulas = {
  event = {
    'onStart',
    'onClick',
    'onClickEnd',
    'onClickMove',
    'onFun',
    'onCollisionStart',
    'onCollisionEnd',
    -- 'onBack',
    -- 'onHide',
    -- 'onView'
  },
  data = {
    'setVar',
    'updVar',
    'setShowText',
    'setHideText',
    'setPosText',
    'setPosXText',
    'setPosYText',
    'setRotationText',
    'setAlphaText',
    'setColorText',
    'setRGBColorText',
    'setHEXColorText',
    'updColorText',
    'updRColorText',
    'updGColorText',
    'updBColorText',
    'setFrontText',
    'setBackText',
    'readVar',
    'writeVar',
    -- 'updTable',
    'setTable',
    'setTable2',
    'setTable3',
    'setTable4',
    'removeTable',
    'removeTable2',
    'removeTable3',
    'removeTable4'
  },
  object = {
    'setPos',
    'setX',
    'setY',
    'setSize',
    'setWidth',
    'setHeight',
    'updX',
    'updY',
    'updSize',
    'updWidth',
    'updHeight',
    'setHide',
    'setView',
    'setRotation',
    'setAlpha',
    'setTag',
    'setFront',
    'setBack',
    'setNameTexture',
    'setIndexTexture',
    'setLinkTexture',
    'resetSize'
  },
  copy = {
    -- 'setCopy',
    -- 'removeCopy',
    -- 'setPosCopy'
  },
  control = {
    'fun',
    'funParams',
    'useTag',
    'if',
    'ifElse',
    'for',
    'enterFrame',
    'timer',
    'groupCreate',
    'groupView',
    'setColorBackground',
    'setRGBColorBackground',
    'setHEXColorBackground',
    -- 'fileLine',
    -- 'fileRead',
    -- 'fileWrite',
    -- 'fileUpdate',
    -- 'fileMove',
    -- 'fileCopy',
    -- 'fileRemove',
    'onMultitouch',
    'offMultitouch',
    'closeApp',
    'commentYourself',
    'else',
    'ifEnd',
    'ifElseEnd',
    'forEnd',
    'enterFrameEnd',
    'useTagEnd',
    -- 'fileLineEnd'
  },
  controlother = {
    'inputText',
    'createTextField',
    'createTextBox',
    'removeTextField',
    'getTextField',
    'setTextField',
    'getOldTextField',
    'setPosField',
    'setSizeField',
    'setHideField',
    'setViewField',
    'setInputTypeField',
    'setEditField',
    'closeKeyboard'
  },
  physics = {
    'setBody',
    'removeBody',
    'setNewBody',
    'setHitboxMesh',
    'setHitboxBox',
    'setHitboxCircle',
    'setGravity',
    'setLinearVelocity',
    'setLinearVelocityX',
    'setLinearVelocityY',
    'setSensor',
    'setNotSensor',
    'setFixedRotation',
    'setNotFixedRotation',
    'setWorldGravity',
    'setVisiblePhysics',
    'setNotVisiblePhysics',
    'setBullet',
    'setNotBullet',
    'setAwake',
    'setAngularVelocity',
    'setAngularDamping',
    'setLinearDamping',
    'setForce',
    'setLinearImpulse',
    'setTorque',
    'setAngularImpulse',
    'setPowerPhysics',
    'startPhysics',
    'stopPhysics'
  },
  physicscopy = {
    -- 'setGravityCopy',
    -- 'setSensorCopy',
    -- 'setPhyRotationCopy'
  },
  network = {
    'openUrl',
    'setGet',
    'setPost'
  }
}
