activity.paramsFormulas = {
  -- event
  ['onStart'] = {},
  ['onClick'] = {},
  ['onClickEnd'] = {},
  ['onClickMove'] = {'value', 'value'},
  ['onFun'] = {'func'},
  ['onCollisionStart'] = {},
  ['onCollisionEnd'] = {},
  ['onClickDisplay'] = {},
  ['onClickDisplayEnd'] = {},
  ['onClickDisplayMove'] = {'value', 'value'},
  ['onBack'] = {},
  ['onHide'] = {},
  ['onView'] = {},

  -- data
  ['setVar'] = {'variable', 'value'},
  ['updVar'] = {'variable', 'value'},
  ['setShowText'] = {'variable', 'font', 'color', 'value', 'value', 'value'},
  ['setHideText'] = {'variable'},
  ['setPosText'] = {'variable', 'value', 'value'},
  ['setPosXText'] = {'variable', 'value'},
  ['setPosYText'] = {'variable', 'value'},
  ['setRotationText'] = {'variable', 'value'},
  ['setAlphaText'] = {'variable', 'value'},
  ['setAlignText'] = {'variable', 'alignX', 'alignY'},
  ['setColorText'] = {'variable', 'color'},
  ['setRGBColorText'] = {'variable', 'value', 'value', 'value'},
  ['setHEXColorText'] = {'variable', 'value'},
  ['updColorText'] = {'variable', 'value'},
  ['updRColorText'] = {'variable', 'value'},
  ['updGColorText'] = {'variable', 'value'},
  ['updBColorText'] = {'variable', 'value'},
  ['setFrontText'] = {'variable'},
  ['setBackText'] = {'variable'},
  ['readVar'] = {'variable'},
  ['writeVar'] = {'variable'},
  ['updTable'] = {'tabl', 'value'},
  ['setTable'] = {'value', 'tabl', 'value'},
  ['removeTable'] = {'tabl', 'value'},

  -- object
  ['setPos'] = {'value', 'value'},
  ['setX'] = {'value'},
  ['setY'] = {'value'},
  ['setSize'] = {'value'},
  ['setWidth'] = {'value'},
  ['setHeight'] = {'value'},
  ['updX'] = {'value'},
  ['updY'] = {'value'},
  ['updSize'] = {'value'},
  ['updWidth'] = {'value'},
  ['updHeight'] = {'value'},
  ['setHide'] = {},
  ['setView'] = {},
  ['setRotation'] = {'value'},
  ['setAlpha'] = {'value'},
  ['updRotation'] = {'value'},
  ['updAlpha'] = {'value'},
  ['setCopy'] = {'setcopy'},
  ['removeCopy'] = {'copy'},
  ['setTag'] = {'tag'},
  ['setFlipX'] = {},
  ['setFlipY'] = {},
  ['setTransitionPos'] = {'value', 'value', 'value'},
  ['setTransitionPosX'] = {'value', 'value'},
  ['setTransitionPosY'] = {'value', 'value'},
  ['setTransitionWidth'] = {'value', 'value'},
  ['setTransitionHeight'] = {'value', 'value'},
  ['setTransitionSize'] = {'value', 'value'},
  ['setTransitionRotation'] = {'value', 'value'},
  ['setTransitionAlpha'] = {'value', 'value'},
  ['setTransitionPosAngle'] = {'value', 'angle', 'value', 'value'},
  ['setAnchorX'] = {'value'},
  ['setAnchorY'] = {'value'},
  ['setFront'] = {},
  ['setBack'] = {},
  ['setNameTexture'] = {'texture'},
  ['setIndexTexture'] = {'value'},
  ['setLinkTexture'] = {'value'},
  ['resetSize'] = {},

  -- control
  ['fun'] = {'func'},
  ['funParams'] = {'func', 'tabl'},
  ['useTag'] = {'tag'},
  ['useTagEnd'] = {},
  ['useCopy'] = {'copy'},
  ['useCopyEnd'] = {},
  ['if'] = {'value'},
  ['ifElse'] = {'value'},
  ['else'] = {},
  ['ifEnd'] = {},
  ['ifElseEnd'] = {},
  ['while'] = {'value'},
  ['whileEnd'] = {},
  ['for'] = {'value'},
  ['forEnd'] = {},
  ['forI'] = {'variable', 'value', 'value', 'value'},
  ['forIEnd'] = {},
  ['forT'] = {'tabl', 'variable', 'variable'},
  ['forTEnd'] = {},
  ['enterFrame'] = {},
  ['enterFrameEnd'] = {},
  ['timer'] = {'value', 'value'},
  ['timerEnd'] = {},
  ['groupCreate'] = {'scene'},
  ['groupView'] = {'scene'},
  ['setColorBackground'] = {'color'},
  ['setRGBColorBackground'] = {'value', 'value', 'value'},
  ['setHEXColorBackground'] = {'value'},
  ['fileLine'] = {'variable', 'value', 'basedir'},
  ['fileLineEnd'] = {},
  ['fileRead'] = {'variable', 'value', 'basedir'},
  ['fileWrite'] = {'value', 'value', 'basedir'},
  ['fileUpdate'] = {'value', 'value', 'basedir'},
  ['fileMove'] = {'value', 'basedir', 'value', 'basedir'},
  ['fileCopy'] = {'value', 'basedir', 'value', 'basedir'},
  ['fileRemove'] = {'value', 'basedir'},
  ['setAccelerometer'] = {},
  ['setAccelerometerInterval'] = {'value'},
  ['setNotifications'] = {'value', 'value', 'sound'},
  ['onMultitouch'] = {},
  ['offMultitouch'] = {},
  ['closeApp'] = {},
  ['commentYourself'] = {'text'},

  -- controlother
  ['inputText'] = {'value', 'variable'},
  ['createTextField'] = {'field', 'value','color', 'value', 'bgfield', 'font'},
  ['createTextBox'] = {'field', 'value','color', 'value', 'bgfield', 'font'},
  ['removeTextField'] = {'field'},
  ['getTextField'] = {'field', 'variable'},
  ['setTextField'] = {'field', 'value'},
  ['getOldTextField'] = {'field', 'variable'},
  ['setPosField'] = {'field', 'value', 'value'},
  ['setSizeField'] = {'field', 'value', 'value'},
  ['setHideField'] = {'field'},
  ['setViewField'] = {'field'},
  ['setInputTypeField'] = {'field', 'typefield'},
  ['setEditField'] = {'field', 'editfield'},
  ['closeKeyboard'] = {},

  -- physics
  ['setBody'] = {'body', 'value', 'value', 'value'},
  ['removeBody'] = {},
  ['setGravity'] = {'value'},
  ['setHitboxMesh'] = {'value'},
  ['setHitboxBox'] = {'editphys'},
  ['setHitboxCircle'] = {'value'},
  ['updHitbox'] = {},
  ['setNewBody'] = {'body'},
  ['setLinearVelocity'] = {'value', 'value'},
  ['setLinearVelocityX'] = {'value'},
  ['setLinearVelocityY'] = {'value'},
  ['setSensor'] = {},
  ['setNotSensor'] = {},
  ['setFixedRotation'] = {},
  ['setNotFixedRotation'] = {},
  ['setWorldGravity'] = {'value', 'value'},
  ['setVisiblePhysics'] = {},
  ['setNotVisiblePhysics'] = {},
  ['setBullet'] = {},
  ['setNotBullet'] = {},
  ['setAwake'] = {},
  ['setAngularVelocity'] = {'value'},
  ['setAngularDamping'] = {'value'},
  ['setLinearDamping'] = {'value'},
  ['setForce'] = {'value', 'value'},
  ['setLinearImpulse'] = {'value', 'value'},
  ['setTorque'] = {'value'},
  ['setAngularImpulse'] = {'value'},
  ['setPowerPhysics'] = {'powerphys'},
  ['startPhysics'] = {},
  ['stopPhysics'] = {},

  -- network
  ['openUrl'] = {'value'},
  ['setGet'] = {'value', 'variable'},
  ['setPost'] = {'value', 'value', 'variable', 'tabl'},
  ['setPut'] = {'value', 'value', 'variable', 'tabl'},
  ['setPatch'] = {'value', 'value', 'variable', 'tabl'},
  ['setDelete'] = {'value', 'variable'},
  ['setToken'] = {'value'},
  ['putFirebase'] = {'value', 'variable', 'value'},
  ['patchFirebase'] = {'value', 'variable', 'value'},
  ['getFirebase'] = {'value', 'variable'},
  ['deleteFirebase'] = {'value', 'variable'}
}

activity.typeFormulas = {
  event = {
    'onStart',
    'onClick',
    'onClickEnd',
    'onClickMove',
    'onFun',
    'onCollisionStart',
    'onCollisionEnd',
    'onBack',
    'onHide',
    'onView'
  },
  data = {
    'setVar',
    'updVar',
    'setShowText',
    'setHideText',
    'setPosText',
    'setPosXText',
    'setPosYText',
    'setRotationText',
    'setAlphaText',
    'setAlignText',
    'setColorText',
    'setRGBColorText',
    'setHEXColorText',
    'updColorText',
    'updRColorText',
    'updGColorText',
    'updBColorText',
    'setFrontText',
    'setBackText',
    'readVar',
    'writeVar',
    'updTable',
    'setTable',
    'removeTable',
  },
  object = {
    'setPos',
    'setX',
    'setY',
    'setSize',
    'setWidth',
    'setHeight',
    'updX',
    'updY',
    'updSize',
    'updWidth',
    'updHeight',
    'setHide',
    'setView',
    'setRotation',
    'setAlpha',
    'updRotation',
    'updAlpha',
    'setCopy',
    'removeCopy',
    'setTag',
    'setFlipX',
    'setFlipY',
    'setTransitionPos',
    'setTransitionPosX',
    'setTransitionPosY',
    'setTransitionWidth',
    'setTransitionHeight',
    'setTransitionSize',
    'setTransitionRotation',
    'setTransitionAlpha',
    'setTransitionPosAngle',
    'setAnchorX',
    'setAnchorY',
    'setFront',
    'setBack',
    'setNameTexture',
    'setIndexTexture',
    'setLinkTexture',
    'resetSize'
  },
  control = {
    'fun',
    'funParams',
    'if',
    'ifElse',
    'for',
    'enterFrame',
    'timer',
    'while',
    'forI',
    'forT',
    'groupCreate',
    'groupView',
    'useTag',
    'useCopy',
    'setColorBackground',
    'setRGBColorBackground',
    'setHEXColorBackground',
    'fileLine',
    'fileRead',
    'fileWrite',
    'fileUpdate',
    'fileMove',
    'fileCopy',
    'fileRemove',
    'setAccelerometer',
    'setAccelerometerInterval',
    'setNotifications',
    'onMultitouch',
    'offMultitouch',
    'closeApp',
    'commentYourself',
    'else',
    'ifEnd',
    'ifElseEnd',
    'forEnd',
    'whileEnd',
    'forIEnd',
    'forTEnd',
    'timerEnd',
    'enterFrameEnd',
    'useTagEnd',
    'useCopyEnd',
    'fileLineEnd'
  },
  controlother = {
    'inputText',
    'createTextField',
    'createTextBox',
    'removeTextField',
    'getTextField',
    'setTextField',
    'getOldTextField',
    'setPosField',
    'setSizeField',
    'setHideField',
    'setViewField',
    'setInputTypeField',
    'setEditField',
    'closeKeyboard'
  },
  physics = {
    'setBody',
    'removeBody',
    'setNewBody',
    'setHitboxMesh',
    'setHitboxBox',
    'setHitboxCircle',
    'updHitbox',
    'setGravity',
    'setLinearVelocity',
    'setLinearVelocityX',
    'setLinearVelocityY',
    'setSensor',
    'setNotSensor',
    'setFixedRotation',
    'setNotFixedRotation',
    'setWorldGravity',
    'setVisiblePhysics',
    'setNotVisiblePhysics',
    'setBullet',
    'setNotBullet',
    'setAwake',
    'setAngularVelocity',
    'setAngularDamping',
    'setLinearDamping',
    'setForce',
    'setLinearImpulse',
    'setTorque',
    'setAngularImpulse',
    'setPowerPhysics',
    'startPhysics',
    'stopPhysics'
  },
  network = {
    'openUrl',
    'setGet',
    'setPost',
    'setPut',
    'setPatch',
    'setDelete',
    'setToken',
    'putFirebase',
    'patchFirebase',
    'getFirebase',
    'deleteFirebase'
  }
}
