activity.paramsFormulas = {
  -- event
  ['onStart'] = {},
  ['onClick'] = {},
  ['onClickEnd'] = {},
  ['onClickMove'] = {'value', 'value'},
  ['onFun'] = {'func'},
  ['onCondition'] = {'value'},
  ['onConditionWhile'] = {'value'},
  ['onCollisionStart'] = {},
  ['onCollisionEnd'] = {},
  ['onClickDisplay'] = {},
  ['onClickDisplayEnd'] = {},
  ['onClickDisplayMove'] = {},
  ['onBack'] = {},
  ['onHide'] = {},
  ['onView'] = {},

  -- data
  ['setVar'] = {'variable', 'value'},
  ['updVar'] = {'variable', 'value'},
  ['setShowText'] = {'value', 'value', 'font', 'value', 'color', 'value'},
  ['setShowText2'] = {'value', 'value', 'font', 'value', 'value', 'value'},
  ['setRemoveText'] = {'value'},
  ['setHideText'] = {'value'},
  ['setViewText'] = {'value'},
  ['setText'] = {'value', 'value'},
  ['setVarText'] = {'value', 'variable'},
  ['setPosText'] = {'value', 'value', 'value'},
  ['setPosXText'] = {'value', 'value'},
  ['setPosYText'] = {'value', 'value'},
  ['setRotationText'] = {'value', 'value'},
  ['setAlphaText'] = {'value', 'value'},
  ['setAlignText'] = {'value', 'alignX', 'alignY'},
  ['setColorText'] = {'value', 'color'},
  ['setRGBColorText'] = {'value', 'value', 'value', 'value'},
  ['setHEXColorText'] = {'value', 'value'},
  ['updColorText'] = {'value', 'value'},
  ['updRColorText'] = {'value', 'value'},
  ['updGColorText'] = {'value', 'value'},
  ['updBColorText'] = {'value', 'value'},
  ['setFrontText'] = {'value'},
  ['setBackText'] = {'value'},
  ['readVar'] = {'variable'},
  ['writeVar'] = {'variable'},
  ['updTable'] = {'tabl', 'value'},
  ['setTable'] = {'value', 'tabl', 'value'},
  ['removeTable'] = {'tabl', 'value'},

  -- object
  ['setPos'] = {'value', 'value'},
  ['setX'] = {'value'},
  ['setY'] = {'value'},
  ['setSize'] = {'value'},
  ['setWidth'] = {'value'},
  ['setHeight'] = {'value'},
  ['updX'] = {'value'},
  ['updY'] = {'value'},
  ['updSize'] = {'value'},
  ['updWidth'] = {'value'},
  ['updHeight'] = {'value'},
  ['setHide'] = {},
  ['setView'] = {},
  ['setRotation'] = {'value'},
  ['setAlpha'] = {'value'},
  ['updRotation'] = {'value'},
  ['updAlpha'] = {'value'},
  ['setTag'] = {'tag'},
  ['setFlipX'] = {},
  ['setFlipY'] = {},
  ['setTransitionPos'] = {'value', 'value', 'value'},
  ['setTransitionPosX'] = {'value', 'value'},
  ['setTransitionPosY'] = {'value', 'value'},
  ['setTransitionWidth'] = {'value', 'value'},
  ['setTransitionHeight'] = {'value', 'value'},
  ['setTransitionSize'] = {'value', 'value'},
  ['setTransitionRotation'] = {'value', 'value'},
  ['setTransitionAlpha'] = {'value', 'value'},
  ['setTransitionPosAngle'] = {'value', 'angle', 'value', 'value'},
  ['setAnchorX'] = {'value'},
  ['setAnchorY'] = {'value'},
  ['setFront'] = {},
  ['setBack'] = {},
  ['setNameTexture'] = {'texture'},
  ['setIndexTexture'] = {'value'},
  ['setLinkTexture'] = {'value'},
  ['setResourceTexture'] = {'resimage'},
  ['resetSize'] = {},

  -- shape
  ['createRect'] = {'value', 'value', 'value', 'value'},
  ['createCircle'] = {'value', 'value'},
  ['createPolygon'] = {'value', 'value'},
  ['createCopy'] = {'value'},
  ['removeShape'] = {'value'},
  ['setListenerShape'] = {'value'},
  ['setSnapshotShape'] = {'value'},
  ['removeListenerShape'] = {'value'},
  ['removeSnapshotShape'] = {'value'},
  ['setPosShape'] = {'value', 'value', 'value'},
  ['setPosXShape'] = {'value', 'value'},
  ['setPosYShape'] = {'value', 'value'},
  ['setSizeShape'] = {'value', 'value'},
  ['setRadiusShape'] = {'value', 'value'},
  ['resetSizeShape'] = {'value'},
  ['setWidthShape'] = {'value', 'value'},
  ['setHeightShape'] = {'value', 'value'},
  ['setNameTextureShape'] = {'value', 'texture'},
  ['setIndexTextureShape'] = {'value', 'value'},
  ['setSdcardTextureShape'] = {'value', 'value'},
  ['setMediaTextureShape'] = {'value'},
  ['setResourceTextureShape'] = {'value', 'resimage'},
  ['updPosXShape'] = {'value', 'value'},
  ['updPosYShape'] = {'value', 'value'},
  ['updSizeShape'] = {'value', 'value'},
  ['updWidthShape'] = {'value', 'value'},
  ['updHeightShape'] = {'value', 'value'},
  ['setHideShape'] = {'value'},
  ['setViewShape'] = {'value'},
  ['setColorShape'] = {'value', 'color'},
  ['setRGBColorShape'] = {'value', 'value', 'value', 'value'},
  ['setHEXColorShape'] = {'value', 'value'},
  ['setRotationShape'] = {'value', 'value'},
  ['setAlphaShape'] = {'value', 'value'},
  ['updRotationShape'] = {'value', 'value'},
  ['updAlphaShape'] = {'value', 'value'},
  ['setFlipXShape'] = {'value'},
  ['setFlipYShape'] = {'value'},
  ['setTransitionPosShape'] = {'value', 'value', 'value', 'value'},
  ['setTransitionPosXShape'] = {'value', 'value', 'value'},
  ['setTransitionPosYShape'] = {'value', 'value', 'value'},
  ['setTransitionWidthShape'] = {'value', 'value', 'value'},
  ['setTransitionHeightShape'] = {'value', 'value', 'value'},
  ['setTransitionSizeShape'] = {'value', 'value', 'value'},
  ['setTransitionRotationShape'] = {'value', 'value', 'value'},
  ['setTransitionAlphaShape'] = {'value', 'value', 'value'},
  ['setTransitionPosAngleShape'] = {'value', 'value', 'angle', 'value', 'value'},
  ['setAnchorShape'] = {'value', 'value', 'value'},
  ['setFrontShape'] = {'value'},
  ['setBackShape'] = {'value'},

  -- tag
  ['setTag'] = {'value'},
  ['setTagShape'] = {'value', 'value'},
  ['setPosTag'] = {'value', 'value', 'value'},
  ['setXTag'] = {'value', 'value'},
  ['setYTag'] = {'value', 'value'},
  ['updXTag'] = {'value', 'value'},
  ['updYTag'] = {'value', 'value'},
  ['setHideTag'] = {'value'},
  ['setViewTag'] = {'value'},
  ['setAlphaTag'] = {'value', 'value'},
  ['updAlphaTag'] = {'value', 'value'},
  ['setTransitionPosTag'] = {'value', 'value', 'value', 'value'},
  ['setTransitionPosXTag'] = {'value', 'value', 'value'},
  ['setTransitionPosYTag'] = {'value', 'value', 'value'},
  ['setTransitionAlphaTag'] = {'value', 'value', 'value'},
  ['setFrontTag'] = {'value'},
  ['setBackTag'] = {'value'},
  ['setXSnapshot'] = {'value'},
  ['setYSnapshot'] = {'value'},
  ['updXSnapshot'] = {'value'},
  ['updYSnapshot'] = {'value'},
  ['setHideSnapshot'] = {},
  ['setViewSnapshot'] = {},
  ['setAlphaSnapshot'] = {'value'},
  ['updAlphaSnapshot'] = {'value'},

  -- control
  ['fun'] = {'func'},
  ['funParams'] = {'func', 'tabl'},
  ['useTag'] = {'tag'},
  ['useTagEnd'] = {},
  ['if'] = {'value'},
  ['ifElse'] = {'value'},
  ['else'] = {},
  ['ifEnd'] = {},
  ['ifElseEnd'] = {},
  ['while'] = {'value'},
  ['whileEnd'] = {},
  ['for'] = {'value'},
  ['forEnd'] = {},
  ['forI'] = {'variable', 'value', 'value', 'value'},
  ['forIEnd'] = {},
  ['forT'] = {'tabl', 'variable', 'variable'},
  ['forTEnd'] = {},
  ['enterFrame'] = {},
  ['enterFrameEnd'] = {},
  ['timer'] = {'value', 'value'},
  ['timerEnd'] = {},
  ['groupCreate'] = {'scene'},
  ['groupView'] = {'scene'},
  ['setColorBackground'] = {'color'},
  ['setPortraitOrientation'] = {},
  ['setLandscapeOrientation'] = {},
  ['setRGBColorBackground'] = {'value', 'value', 'value'},
  ['setHEXColorBackground'] = {'value'},
  ['fileLine'] = {'variable', 'value', 'basedir'},
  ['fileLineEnd'] = {},
  ['fileRead'] = {'variable', 'value', 'basedir'},
  ['fileWrite'] = {'value', 'value', 'basedir'},
  ['fileUpdate'] = {'value', 'value', 'basedir'},
  ['fileMove'] = {'value', 'basedir', 'value', 'basedir'},
  ['fileCopy'] = {'value', 'basedir', 'value', 'basedir'},
  ['fileRemove'] = {'value', 'basedir'},
  ['setAccelerometer'] = {},
  ['setAccelerometerInterval'] = {'value'},
  ['setNotifications'] = {'value', 'value', 'ressound'},
  ['onMultitouch'] = {},
  ['offMultitouch'] = {},
  ['closeApp'] = {},
  ['commentYourself'] = {'text'},

  -- controlother
  ['playSound'] = {'ressound', 'value'},
  ['pauseSound'] = {'ressound'},
  ['resumeSound'] = {'ressound'},
  ['rewindSound'] = {'ressound', 'value'},
  ['setVolumeSound'] = {'ressound', 'value'},
  ['setTotalVolumeSound'] = {'value'},
  ['stopSound'] = {},
  ['createVideo'] = {'value', 'resvideo'},
  ['createLinkVideo'] = {'value', 'value'},
  ['rewindVideo'] = {'value', 'value'},
  ['playVideo'] = {'value'},
  ['pauseVideo'] = {'value'},
  ['viewVideo'] = {'value'},
  ['hideVideo'] = {'value'},
  ['muteVideo'] = {'value'},
  ['unmuteVideo'] = {'value'},
  ['setPosVideo'] = {'value', 'value', 'value'},
  ['setWidthVideo'] = {'value', 'value'},
  ['inputText'] = {'value', 'variable'},
  ['createTextField'] = {'value', 'value','color', 'value', 'bgfield', 'font'},
  ['createTextBox'] = {'value', 'value','color', 'value', 'bgfield', 'font'},
  ['removeTextField'] = {'value'},
  ['getTextField'] = {'value', 'variable'},
  ['setTextField'] = {'value', 'value'},
  ['getOldTextField'] = {'value', 'variable'},
  ['setPosField'] = {'value', 'value', 'value'},
  ['setSizeField'] = {'value', 'value', 'value'},
  ['setHideField'] = {'value'},
  ['setViewField'] = {'value'},
  ['setInputTypeField'] = {'value', 'typefield'},
  ['setEditField'] = {'value', 'editfield'},
  ['closeKeyboard'] = {},
  ['createEmitter'] = {'value', 'emitter'},
  ['setPosEmitter'] = {'value', 'value', 'value'},
  ['setSizeEmitter'] = {'value', 'value'},
  ['setSpeedEmitter'] = {'value', 'value'},
  ['setRotationEmitter'] = {'value', 'value'},
  ['setGravityEmitter'] = {'value', 'value', 'value'},
  ['removeEmitter'] = {'value'},
  ['removeAllEmitter'] = {},
  ['setStartRedColorEmitter'] = {'value', 'value'},
  ['setStartGreenColorEmitter'] = {'value', 'value'},
  ['setStartBlueColorEmitter'] = {'value', 'value'},
  ['setStartAlphaColorEmitter'] = {'value', 'value'},
  ['setFinishRedColorEmitter'] = {'value', 'value'},
  ['setFinishGreenColorEmitter'] = {'value', 'value'},
  ['setFinishBlueColorEmitter'] = {'value', 'value'},
  ['setFinishAlphaColorEmitter'] = {'value', 'value'},

  -- physics (objects)
  ['setBody'] = {'body', 'value', 'value', 'value'},
  ['removeBody'] = {},
  ['setGravity'] = {'value'},
  ['setHitboxMesh'] = {'value'},
  ['setHitboxBox'] = {'editphys'},
  ['setHitboxCircle'] = {'value'},
  ['updHitbox'] = {},
  ['setNewBody'] = {'body'},
  ['setLinearVelocity'] = {'value', 'value'},
  ['setLinearVelocityX'] = {'value'},
  ['setLinearVelocityY'] = {'value'},
  ['setSensor'] = {},
  ['setNotSensor'] = {},
  ['setFixedRotation'] = {},
  ['setNotFixedRotation'] = {},
  ['setWorldGravity'] = {'value', 'value'},
  ['setVisiblePhysics'] = {},
  ['setNotVisiblePhysics'] = {},
  ['setBullet'] = {},
  ['setNotBullet'] = {},
  ['setAwake'] = {},
  ['setAngularVelocity'] = {'value'},
  ['setAngularDamping'] = {'value'},
  ['setLinearDamping'] = {'value'},
  ['setForce'] = {'value', 'value'},
  ['setLinearImpulse'] = {'value', 'value'},
  ['setTorque'] = {'value'},
  ['setAngularImpulse'] = {'value'},
  ['setPowerPhysics'] = {'powerphys'},
  ['startPhysics'] = {},
  ['stopPhysics'] = {},

  -- physics (shape)
  ['setBodyShape'] = {'value', 'body', 'value', 'value', 'value'},
  ['removeBodyShape'] = {'value'},
  ['setGravityShape'] = {'value', 'value'},
  ['setHitboxMeshShape'] = {'value', 'value'},
  ['setHitboxCircleShape'] = {'value', 'value'},
  ['updHitboxShape'] = {'value'},
  ['setNewBodyShape'] = {'value', 'body'},
  ['setLinearVelocityShape'] = {'value', 'value', 'value'},
  ['setLinearVelocityXShape'] = {'value', 'value'},
  ['setLinearVelocityYShape'] = {'value', 'value'},
  ['setSensorShape'] = {'value'},
  ['setNotSensorShape'] = {'value'},
  ['setFixedRotationShape'] = {'value'},
  ['setNotFixedRotationShape'] = {'value'},
  ['setBulletShape'] = {'value'},
  ['setNotBulletShape'] = {'value'},
  ['setAwakeShape'] = {'value'},
  ['setAngularVelocityShape'] = {'value', 'value'},
  ['setAngularDampingShape'] = {'value', 'value'},
  ['setLinearDampingShape'] = {'value', 'value'},
  ['setForceShape'] = {'value', 'value', 'value'},
  ['setLinearImpulseShape'] = {'value', 'value', 'value'},
  ['setTorqueShape'] = {'value', 'value'},
  ['setAngularImpulseShape'] = {'value', 'value'},

  -- network
  ['openUrl'] = {'value'},
  ['setGet'] = {'value', 'variable'},
  ['setPost'] = {'value', 'value', 'variable', 'tabl'},
  ['setPut'] = {'value', 'value', 'variable', 'tabl'},
  ['setPatch'] = {'value', 'value', 'variable', 'tabl'},
  ['setDelete'] = {'value', 'variable'},
  ['setToken'] = {'value'},
  ['putFirebase'] = {'value', 'variable', 'value'},
  ['patchFirebase'] = {'value', 'variable', 'value'},
  ['getFirebase'] = {'value', 'variable'},
  ['deleteFirebase'] = {'value', 'variable'}
}

activity.typeFormulas = {
  event = {
    'onStart',
    'onClick',
    'onClickEnd',
    'onClickMove',
    'onFun',
    'onCondition',
    'onConditionWhile',
    'onCollisionStart',
    'onCollisionEnd',
    'onClickDisplay',
    'onClickDisplayEnd',
    'onClickDisplayMove',
    'onBack',
    'onHide',
    'onView'
  },
  data = {
    'setVar',
    'updVar',
    'setShowText',
    'setShowText2',
    'setText',
    -- 'setVarText',
    'setPosText',
    'setPosXText',
    'setPosYText',
    'setRotationText',
    'setAlphaText',
    'setAlignText',
    'setColorText',
    'setRGBColorText',
    'setHEXColorText',
    'setRemoveText',
    'setHideText',
    'setViewText',
    'updColorText',
    'updRColorText',
    'updGColorText',
    'updBColorText',
    'setFrontText',
    'setBackText',
    'readVar',
    'writeVar',
    'updTable',
    'setTable',
    'removeTable'
  },
  object = {
    'setPos',
    'setX',
    'setY',
    'setSize',
    'setWidth',
    'setHeight',
    'updX',
    'updY',
    'updSize',
    'updWidth',
    'updHeight',
    'setHide',
    'setView',
    'setRotation',
    'setAlpha',
    'updRotation',
    'updAlpha',
    'setFlipX',
    'setFlipY',
    'setTransitionPos',
    'setTransitionPosX',
    'setTransitionPosY',
    'setTransitionWidth',
    'setTransitionHeight',
    'setTransitionSize',
    'setTransitionRotation',
    'setTransitionAlpha',
    'setTransitionPosAngle',
    'setAnchorX',
    'setAnchorY',
    'setFront',
    'setBack',
    'setNameTexture',
    'setIndexTexture',
    'setLinkTexture',
    'setResourceTexture',
    'resetSize'
  },
  shape = {
    'createRect',
    'createCircle',
    'createPolygon',
    'createCopy',
    'removeShape',
    'setListenerShape',
    'setSnapshotShape',
    'removeListenerShape',
    'removeSnapshotShape',
    'setPosShape',
    'setPosXShape',
    'setPosYShape',
    'setSizeShape',
    'setRadiusShape',
    'resetSizeShape',
    'setWidthShape',
    'setHeightShape',
    'setNameTextureShape',
    'setIndexTextureShape',
    'setSdcardTextureShape',
    'setMediaTextureShape',
    'setResourceTextureShape',
    'updPosXShape',
    'updPosYShape',
    'updSizeShape',
    'updWidthShape',
    'updHeightShape',
    'setHideShape',
    'setViewShape',
    'setColorShape',
    'setRGBColorShape',
    'setHEXColorShape',
    'setRotationShape',
    'setAlphaShape',
    'updRotationShape',
    'updAlphaShape',
    'setFlipXShape',
    'setFlipYShape',
    'setTransitionPosShape',
    'setTransitionPosXShape',
    'setTransitionPosYShape',
    'setTransitionWidthShape',
    'setTransitionHeightShape',
    'setTransitionSizeShape',
    'setTransitionRotationShape',
    'setTransitionAlphaShape',
    'setTransitionPosAngleShape',
    'setAnchorShape',
    'setFrontShape',
    'setBackShape'
  },
  tag = {
    'setTag',
    'setTagShape',
    'setPosTag',
    'setXTag',
    'setYTag',
    'setAlphaTag',
    'updXTag',
    'updYTag',
    'updAlphaTag',
    'setHideTag',
    'setViewTag',
    'setTransitionPosTag',
    'setTransitionPosXTag',
    'setTransitionPosYTag',
    'setTransitionAlphaTag',
    'setFrontTag',
    'setBackTag',
    'setXSnapshot',
    'setYSnapshot',
    'updXSnapshot',
    'updYSnapshot',
    'setHideSnapshot',
    'setViewSnapshot',
    'setAlphaSnapshot',
    'updAlphaSnapshot'
  },
  control = {
    'fun',
    'funParams',
    'if',
    'ifElse',
    'for',
    'enterFrame',
    'timer',
    'while',
    'forI',
    'forT',
    'groupCreate',
    'groupView',
    'setColorBackground',
    'setRGBColorBackground',
    'setHEXColorBackground',
    'setPortraitOrientation',
    'setLandscapeOrientation',
    'fileLine',
    'fileRead',
    'fileWrite',
    'fileUpdate',
    'fileMove',
    'fileCopy',
    'fileRemove',
    'setAccelerometer',
    'setAccelerometerInterval',
    'setNotifications',
    'onMultitouch',
    'offMultitouch',
    'closeApp',
    'commentYourself',
    'else',
    'ifEnd',
    'ifElseEnd',
    'forEnd',
    'whileEnd',
    'forIEnd',
    'forTEnd',
    'timerEnd',
    'enterFrameEnd',
    'useTagEnd',
    'useCopyEnd',
    'fileLineEnd'
  },
  controlother = {
    'playSound',
    'pauseSound',
    'resumeSound',
    'rewindSound',
    'setVolumeSound',
    'setTotalVolumeSound',
    'stopSound',
    'createVideo',
    'createLinkVideo',
    'rewindVideo',
    'playVideo',
    'pauseVideo',
    'viewVideo',
    'hideVideo',
    'muteVideo',
    'unmuteVideo',
    'setPosVideo',
    'setWidthVideo',
    'inputText',
    'createTextField',
    'createTextBox',
    'removeTextField',
    'getTextField',
    'setTextField',
    'getOldTextField',
    'setPosField',
    'setSizeField',
    'setHideField',
    'setViewField',
    'setInputTypeField',
    'setEditField',
    'closeKeyboard',
    'createEmitter',
    'setPosEmitter',
    'setSizeEmitter',
    'setSpeedEmitter',
    'setRotationEmitter',
    'setGravityEmitter',
    'removeEmitter',
    'removeAllEmitter',
    'setStartRedColorEmitter',
    'setStartGreenColorEmitter',
    'setStartBlueColorEmitter',
    'setStartAlphaColorEmitter',
    'setFinishRedColorEmitter',
    'setFinishGreenColorEmitter',
    'setFinishBlueColorEmitter',
    'setFinishAlphaColorEmitter'
  },
  physics = {
    'setBody',
    'removeBody',
    'setNewBody',
    'setHitboxMesh',
    'setHitboxBox',
    'setHitboxCircle',
    'updHitbox',
    'setGravity',
    'setLinearVelocity',
    'setLinearVelocityX',
    'setLinearVelocityY',
    'setSensor',
    'setNotSensor',
    'setFixedRotation',
    'setNotFixedRotation',
    'setWorldGravity',
    'setVisiblePhysics',
    'setNotVisiblePhysics',
    'setBullet',
    'setNotBullet',
    'setAwake',
    'setAngularVelocity',
    'setAngularDamping',
    'setLinearDamping',
    'setForce',
    'setLinearImpulse',
    'setTorque',
    'setAngularImpulse',
    'setPowerPhysics',
    'startPhysics',
    'stopPhysics'
  },
  physicsshape = {
    'setBodyShape',
    'removeBodyShape',
    'setGravityShape',
    'setHitboxMeshShape',
    'setHitboxCircleShape',
    'updHitboxShape',
    'setNewBodyShape',
    'setLinearVelocityShape',
    'setLinearVelocityXShape',
    'setLinearVelocityYShape',
    'setSensorShape',
    'setNotSensorShape',
    'setFixedRotationShape',
    'setNotFixedRotationShape',
    'setBulletShape',
    'setNotBulletShape',
    'setAwakeShape',
    'setAngularVelocityShape',
    'setAngularDampingShape',
    'setLinearDampingShape',
    'setForceShape',
    'setLinearImpulseShape',
    'setTorqueShape',
    'setAngularImpulseShape'
  },
  network = {
    'openUrl',
    'setGet',
    'setPost',
    'setPut',
    'setPatch',
    'setDelete',
    'setToken',
    'putFirebase',
    'patchFirebase',
    'getFirebase',
    'deleteFirebase'
  }
}
