stringsLanguage = {
  langs = {
    {'ru', 'Русский'},
    {'en', 'English'},
    -- {'in', 'हिन्दी'},
    -- {'cn', '中文'},
    -- {'es', 'Español'},
  },
  ['ru'] = {
    blocks = {
      -- event
      ['onStart'] = {'При старте'},
      ['onClick'] = {'Когда палец прикасается к объекту'},
      ['onClickEnd'] = {'Когда палец отпускает объект'},
      ['onClickMove'] = {'Когда палец находится на экране', {'Смещение (X):', 'Смещение (Y):'}},
      ['onFun'] = {'Когда будет получена функция', {'Название функции:'}},
      ['onCollisionStart'] = {'Когда коллизия произойдёт'},
      ['onCollisionEnd'] = {'Когда коллизия закончится'},
      ['onBack'] = {'При нажатии на кнопку "Назад"'},
      ['onHide'] = {'Приложение свернули с главного экрана'},
      ['onView'] = {'Приложение вернули на главный экран'},

      -- data
      ['setVar'] = {'Установить значение переменной', {'Название переменной:', 'Значение:'}},
      ['updVar'] = {'Добавить значение к переменной', {'Название переменной:', 'Значение:'}},
      ['setShowText'] = {'Создать текст на экране', {'Название переменной:', 'Шрифт:', 'Выровнять:', 'Размер:', 'Ширина:', 'Высота:'}},
      ['setHideText'] = {'Удалить текст с экрана', {'Название переменной:'}},
      ['setPosText'] = {'Установить позицию текста', {'Название переменной:', 'Значение (X):', 'Значение (Y)'}},
      ['setPosXText'] = {'Установить позицию X текста', {'Название переменной:', 'Значение (X):'}},
      ['setPosYText'] = {'Установить позицию Y текста', {'Название переменной:', 'Значение (Y):'}},
      ['setRotationText'] = {'Установить вращение текста', {'Название переменной:', 'Значение (0-360):'}},
      ['setAlignText'] = {'Установить выравнивание текста', {'Название переменной:', 'Выровнять:'}},
      ['setAlphaText'] = {'Установить прозрачность текста', {'Название переменной:', 'Значение (0-100):'}},
      ['setColorText'] = {'Установить цвет текста', {'Название переменной:', 'Цвет:'}},
      ['setRGBColorText'] = {'Установить rgb цвет текста', {'Название переменной:', 'Значение r (0-255):', 'Значение g (0-255):', 'Значение b (0-255):'}},
      ['setHEXColorText'] = {'Установить hex цвет текста', {'Название переменной:', 'Значение hex:'}},
      ['updColorText'] = {'Изменить цвет текста', {'Название переменной:', 'Значение (0-255):'}},
      ['updRColorText'] = {'Изменить красный цвет текста', {'Название переменной:', 'Значение (0-255):'}},
      ['updGColorText'] = {'Изменить зелёный цвет текста', {'Название переменной:', 'Значение (0-255):'}},
      ['updBColorText'] = {'Изменить синий цвет текста', {'Название переменной:', 'Значение (0-255):'}},
      ['setFrontText'] = {'Разместить текст на слой выше', {'Название переменной:'}},
      ['setBackText'] = {'Разместить текст на слой ниже', {'Название переменной:'}},
      ['readVar'] = {'Считать переменную', {'Название переменной:'}},
      ['writeVar'] = {'Сохранить переменную', {'Название переменной:'}},
      ['updTable'] = {'Перезаписать таблицу', {'Название таблицы:', 'Значение:'}},
      ['setTable'] = {'Установить элемент в таблицу (1)', {'Название таблицы:', 'Ключ (1):', 'Значение:'}},
      ['setTable2'] = {'Установить элемент в таблицу (2)', {'Название таблицы:', 'Значение:', 'Ключ (1):', 'Ключ (2):'}},
      ['setTable3'] = {'Установить элемент в таблицу (3)', {'Название таблицы:', 'Ключ (1):', 'Ключ (2):', 'Ключ (3):', 'Значение:'}},
      ['setTable4'] = {'Установить элемент в таблицу (4)', {'Название таблицы:', 'Значение:', 'Ключ (1):', 'Ключ (2):', 'Ключ (3):', 'Ключ (4):'}},
      ['removeTable'] = {'Удалить элемент из таблицы (1)', {'Название таблицы:', 'Ключ (1):'}},
      ['removeTable2'] = {'Удалить элемент из таблицы (2)', {'Название таблицы:', 'Ключ (1):', 'Ключ (2):'}},
      ['removeTable3'] = {'Удалить элемент из таблицы (3)', {'Название таблицы:', 'Ключ (1):', 'Ключ (2):', 'Ключ (3):'}},
      ['removeTable4'] = {'Удалить элемент из таблицы (4)', {'Название таблицы:', 'Ключ (1):', 'Ключ (2):', 'Ключ (3):', 'Ключ (4):'}},

      -- object
      ['setPos'] = {'Установить позицию', {'Значение (X):', 'Значение (Y):'}},
      ['setX'] = {'Установить позицию X', {'Значение (X):'}},
      ['setY'] = {'Установить позицию Y', {'Значение (Y):'}},
      ['setSize'] = {'Установить размер', {'Значение (%):'}},
      ['setWidth'] = {'Установить ширину', {'Значение:'}},
      ['setHeight'] = {'Установить высоту', {'Значение:'}},
      ['updX'] = {'Изменить позицию X', {'Значение (X):'}},
      ['updY'] = {'Изменить позицию Y', {'Значение (Y):'}},
      ['updSize'] = {'Изменить размер', {'Значение (%):'}},
      ['updWidth'] = {'Изменить ширину', {'Значение:'}},
      ['updHeight'] = {'Изменить высоту', {'Значение:'}},
      ['setHide'] = {'Скрыть объект с экрана'},
      ['setView'] = {'Показать объект на экране'},
      ['setRotation'] = {'Установить вращение', {'Значение (0-360):'}},
      ['setAlpha'] = {'Установить прозрачность', {'Значение (0-100):'}},
      ['setTag'] = {'Присвоить к тегу', {'Имя тега:'}},
      ['setFront'] = {'Разместить на слой выше'},
      ['setBack'] = {'Разместить на слой ниже'},
      ['setNameTexture'] = {'Установить текстуру по имени', {'Имя текстуры:'}},
      ['setIndexTexture'] = {'Установить текстуру по индексу', {'Индекс текстуры:'}},
      ['setLinkTexture'] = {'Установить текстуру по ссылке', {'Значение (Ссылка):'}},
      ['resetSize'] = {'Установить размер по текстуре'},

      -- control
      ['fun'] = {'Вызвать функцию', {'Название функции:'}},
      ['funParams'] = {'Вызвать функцию с параметрами', {'Название функции:', 'Название таблицы:'}},
      ['useTag'] = {'Использовать блоки для тега', {'Имя тега:'}},
      ['useTagEnd'] = {'Конец использования тега'},
      ['if'] = {'Если условие истина', {'Условие:'}},
      ['ifElse'] = {'Если условие истина, Иначе', {'Условие:'}},
      ['else'] = {'Иначе'},
      ['ifEnd'] = {'Конец условия'},
      ['ifElseEnd'] = {'Конец условия'},
      ['for'] = {'Повторить N раз', {'Количество повторов (N):'}},
      ['forEnd'] = {'Конец цикла'},
      ['enterFrame'] = {'Повторять вечно'},
      ['enterFrameEnd'] = {'Конец вечности'},
      ['timer'] = {'Таймер', {'Значение (Секунды):', 'Кол-во повторений:'}},
      ['groupCreate'] = {'Создать группу', {'Название группы:'}},
      ['groupView'] = {'Показать группу', {'Название группы:'}},
      ['setColorBackground'] = {'Установить цвет фона', {'Цвет:'}},
      ['setRGBColorBackground'] = {'Установить rgb цвет фона', {'Значение r (0-255):', 'Значение g (0-255):', 'Значение b (0-255):'}},
      ['setHEXColorBackground'] = {'Установить hex цвет фона', {'Значение hex:'}},
      ['fileLine'] = {'Прочитать файл по строкам', {'Название переменной:', 'Путь к файлу:', 'Каталог:'}},
      ['fileLineEnd'] = {'Конец прочтения файла'},
      ['fileRead'] = {'Прочитать файл', {'Название переменной:', 'Путь к файлу:', 'Каталог:'}},
      ['fileWrite'] = {'Перезаписать файл', {'Значение:', 'Путь к файлу:', 'Каталог:'}},
      ['fileUpdate'] = {'Записать в конец файла', {'Значение:', 'Путь к файлу:', 'Каталог:'}},
      ['fileMove'] = {'Переместить/переименовать файл', {'Путь к файлу (1):', 'Каталог (1):', 'Путь к файлу (2):', 'Каталог (2):'}},
      ['fileCopy'] = {'Копировать файл', {'Путь к файлу (1):', 'Каталог (1):', 'Путь к файлу (2):', 'Каталог (2):'}},
      ['fileRemove'] = {'Удалить файл', {'Путь к файлу:', 'Каталог:'}},
      ['onMultitouch'] = {'Активировать мультикасания'},
      ['offMultitouch'] = {'Деактивировать мультикасания'},
      ['closeApp'] = {'Закрыть приложение'},
      ['commentYourself'] = {'Комментарий (для себя)', {'Комментарий:'}},

      -- controlother
      ['inputText'] = {'Получить текст от пользователя', {'Текст для пользователя:', 'Название переменной:'}},
      ['createTextField'] = {'Создать однострочное текстовое поле', {'Text field:', 'Текст для пользователя:', 'Цвет:', 'Размер:', 'Фон поля:', 'Шрифт:'}},
      ['createTextBox'] = {'Создать многострочное текстовое поле', {'Text field:', 'Текст для пользователя:', 'Цвет:', 'Размер:', 'Фон поля:', 'Шрифт:'}},
      ['removeTextField'] = {'Удалить текстовое поле', {'Text field:'}},
      ['getTextField'] = {'Получить текст', {'Text field:', 'Название переменной:'}},
      ['setTextField'] = {'Установить текст', {'Text field:', 'Значение (Текст):'}},
      ['getOldTextField'] = {'Получить старый текст', {'Text field:', 'Название переменной:'}},
      ['setPosField'] = {'Установить позицию текстового поля', {'Text field:', 'Значение (X):', 'Значение (Y):'}},
      ['setSizeField'] = {'Установить размеры текстового поля', {'Text field:', 'Значение (Ширина):', 'Значение (Высота):'}},
      ['setHideField'] = {'Спрятать текстовое поле', {'Text field:'}},
      ['setViewField'] = {'Показать текстовое поле', {'Text field:'}},
      ['setInputTypeField'] = {'Установить тип ввода', {'Text field:', 'Тип ввода:'}},
      ['setEditField'] = {'Разрешение на редактирование', {'Text field:', 'Разрешение:'}},
      ['closeKeyboard'] = {'Выключить экранную клавиатуру'},

      -- physics
      ['setBody'] = {'Добавить физическое тело', {'Тип:', 'Плотность:', 'Прыгучесть:', 'Трение:'}},
      ['removeBody'] = {'Удалить физическое тело'},
      ['setNewBody'] = {'Установить тип', {'Тип:'}},
      ['setHitboxMesh'] = {'Установить хитбокс (меш)', {'Грубость текселей:'}},
      ['setHitboxBox'] = {'Установить хитбокс (конструкции)', {'Хитбокс:'}},
      ['setHitboxCircle'] = {'Установить хитбокс (круг)', {'Значение (Радиус):'}},
      ['setGravity'] = {'Установить гравитацию', {'Значение (Гравитация):'}},
      ['setLinearVelocity'] = {'Сделать прыжок', {'Значение (X):', 'Значение (Y):'}},
      ['setLinearVelocityX'] = {'Сделать прыжок по X', {'Значение (X):'}},
      ['setLinearVelocityY'] = {'Сделать прыжок по Y', {'Значение (Y):'}},
      ['setSensor'] = {'Установить режим датчика'},
      ['setNotSensor'] = {'Удалить режим датчика'},
      ['setFixedRotation'] = {'Сделать тело невращаемым'},
      ['setNotFixedRotation'] = {'Сделать тело вращаемым'},
      ['setWorldGravity'] = {'Установить общую гравитацию', {'Значение (X):', 'Значение (Y):'}},
      ['setVisiblePhysics'] = {'Показать хитбоксы'},
      ['setNotVisiblePhysics'] = {'Скрыть хитбоксы'},
      ['setBullet'] = {'Установить свойство пули'},
      ['setNotBullet'] = {'Удалить свойство пули'},
      ['setAwake'] = {'Разбудить'},
      ['setAngularVelocity'] = {'Установить угловую скорость', {'Значение:'}},
      ['setAngularDamping'] = {'Установить угловое затухание', {'Значение:'}},
      ['setLinearDamping'] = {'Установить линейное затухание', {'Значение:'}},
      ['setForce'] = {'Применить силу', {'Значение (X):', 'Значение (Y):'}},
      ['setLinearImpulse'] = {'Применить линейный импульс', {'Значение (X):', 'Значение (Y):'}},
      ['setTorque'] = {'Применить вращающую силу', {'Значение:'}},
      ['setAngularImpulse'] = {'Применить угловой импульс', {'Значение:'}},
      ['setPowerPhysics'] = {'Установить мощность физики', {'Вычислительная мощность:'}},
      ['startPhysics'] = {'Включить физику'},
      ['stopPhysics'] = {'Выключить физику'},

      -- network
      ['openUrl'] = {'Открыть ссылку в браузере', {'Значение (Ссылка):'}},
      ['setGet'] = {'GET запрос', {'Значение (Ссылка):', 'Название переменной:'}},
      ['setPost'] = {'POST запрос', {'Значение (Ссылка):', 'Body:', 'Название переменной:', 'Headers:'}}
    },
    editorList = {
      fun = {
        -- {'декодировать_json', 'decode_json'},
        {'корень', 'radical'},
        {'рандом', 'random'},
        {'округлить', 'round'},
        {'остаток', '%'},
        {'синус', 'sin'},
        {'косинус', 'cos'},
        {'тангенс', 'tan'},
        {'котангенс', 'ctan'},
        {'арксинус', 'arcsin'},
        {'арккосинус', 'arccos'},
        {'арктангенс', 'arctan'},
        {'арккотангенс', 'arcctan'},
        {'натуральный_логарифм', 'log'},
        {'десятичный_логарифм', 'log10'},
        {'pi', 'pi'},
        {'время_unix', 'unix_time'},
      },
      prop = {
        {'позицияX', 'posX'},
        {'позицияY', 'posY'},
        {'позицияZ', 'posZ'},
        {'ширина', 'width'},
        {'высота', 'height'},
        {'угол', 'rotation'},
        {'тег', 'tag'},
      },
      log = {
        {'истина', 'true'},
        {'ложь', 'false'},
        {'=', '='},
        {'>', '>'},
        {'<', '<'},
        {'>=', '>='},
        {'<=', '<='},
        {'~=', '~='},
        {'и', 'and'},
        {'или', 'or'},
        {'не', 'not'},
      },
    },
    offMagnetX = 'Выключить магнит по X',
    offMagnetY = 'Выключить магнит по Y',
    onMagnetX = 'Включить магнит по X',
    onMagnetY = 'Включить магнит по Y',
    saveAndExit = 'Сохранить хитбокс и выйти',
    index = 'Индекс: ',
    indexBox = 'Индекс конструкции',
    viewIndexBox = 'Показать индекс конструкции',
    viewLines = 'Показать линии',
    hideLines = 'Скрыть линии',
    onPhysics = 'Включить физику',
    viewHitbox = 'Показать хитбокс',
    hideHitbox = 'Скрыть хитбокс',
    addBox = 'Добавить конструкцию',
    removeBox = 'Удалить конструкцию',
    addPoint = 'Добавить точку',
    removePoint = 'Удалить точку',
    shapephyscircle = 'Круг',
    shapephysbox = 'Конструкции',
    shapephysmesh = 'Меш',
    editfieldtrue = 'Можно ред.',
    editfieldfalse = 'Нельзя ред.',
    typefielddefault = 'По умолчанию',
    typefieldnumber = 'Цифровая',
    typefielddecimal = 'Десятичные значения',
    typefieldphone = 'Номер телефона',
    typefieldurl = 'Ссылка',
    typefieldemail = 'Эл. адрес',
    typefieldnoemoji = 'Без смайликов',
    bgfieldtrue = 'Оставить',
    bgfieldfalse = 'Убрать',
    resourcesTitle = 'Ресурсы',
    resource = 'Управлять ресурсами',
    leftAlign = 'Слева',
    centerAlign = 'По центру',
    rightAlign = 'Справа',
    inputHexTitle = 'Введите hex',
    inputHexText = 'Введите hex (например, #FFFFFF)',
    red = 'Красный:',
    green = 'Зелёный:',
    blue = 'Синий:',
    isNotPhyRotation = 'Невращаемый',
    isPhyRotation = 'Вращаемый',
    isSensor = 'Невидимый',
    isNotSensor = 'Видимый',
    staticBody = 'Статическое',
    dynamicBody = 'Динамическое',
    currentCopy = 'Текущая',
    lastCopy = 'Последняя',
    allCopy = 'Все',
    selfCopy = 'Себя',
    newfieldTitle = 'Назовите текстовое поле',
    newfieldText = 'Напишите имя для нового текстового поля',
    newfield = 'Создать текстовое поле',
    newtagTitle = 'Назовите тег',
    newtagText = 'Напишите имя для нового тега',
    newtag = 'Создать тег',
    newfuncTitle = 'Назовите функцию',
    newfuncText = 'Напишите название для новой функции',
    newfunc = 'Создать функцию',
    newtablTitle = 'Назовите таблицу',
    newtablText = 'Напишите название для новой таблицы',
    newtabl = 'Создать таблицу',
    newvariableTitle = 'Назовите переменную',
    newvariableText = 'Напишите название для новой переменной',
    newvariable = 'Создать переменную',
    editorVar = 'Переменные',
    editorTable = 'Таблицы',
    editorFun = 'Функции',
    editorProp = 'Свойства',
    editorLog = 'Логика',
    editorObj = 'Объекты',
    editorDevice = 'Устройство',
    editorLocalTable = 'локал',
    editorInputLocal = 'Локал',
    editorInputText = 'Текст',
    editorTitle = 'Редактор выражений',
    typeevent = 'События',
    typedata = 'Данные',
    typeobject = 'Объекты',
    -- typecopy = 'Копии',
    typecontrol = 'Управление',
    typecontrolother = 'Другое',
    typephysics = 'Физика',
    -- typephysicscopy = 'Физика (Копии)',
    typenetwork = 'Интернет',
    typenot = 'Что-то будет',
    newblocksTitle = 'Новый блок',
    blocksTitle = 'Блоки',
    close = 'Закрыть',
    errorPermissionText = 'Если Construct Code автоматически не запросил доступ к хранилищу, то сделайте это пожалуйста вручную в настройках вашего телефона, приятной разработки',
    errorPermissionTitle = 'Ошибка доступа',
    noTexture = 'Без текстуры',
    firstScene = 'Основная группа',
    changeTexture = 'Сменить текстуру',
    texturesTitle = 'Текстуры',
    enterTitleTextureText = 'Имя новой текстуры...',
    enterNewTitleTextureText = 'Введите новое имя текстуры...',
    myProgramText = 'Мои программы',
    continueText = 'Продолжить',
    settingsText = 'Настройки',
    buttonInput = 'Ок',
    settingsTitle = 'Настройки',
    settingsStdImport = 'Стандартный импорт картинок',
    settingsPictureView = 'Показывать иллюстрации',
    settingsLanguage = 'Язык приложения',
    social = 'Социальные сети',
    socialText = 'Перейти в оффициальные группы/каналы программы',
    vk = 'Вконтакте',
    tg = 'Телеграм',
    objectsTitle = 'Объекты',
    scenesTitle = 'Группы',
    programsTitle = 'Мои программы',
    chooseOrientation = 'Выберите ориентацию',
    chooseOrientationText = 'Выберите ориентацию для нового проекта\nПортретный: 720x1280\nЛандшафтный: 1280x720',
    portrait = 'Портретный',
    landscape = 'Ландшафтный',
    whichObject = 'Какой объект создать?',
    chooseTypeObject = 'Выберите, какой тип объекта вы хотите создать',
    noPixelImage = 'Не пиксельную картинку',
    pixelImage = 'Пиксельную картинку',
    enterTextDescription = 'Введите текст, который хотите добавить',
    enterText = 'Введите текст',
    enterName = 'Введите имя',
    enterTitle = 'Введите название',
    enterTitleProgramText = 'Название нового проекта...',
    enterTitleResourceText = 'Название нового ресурса...',
    enterTitleSceneText = 'Название новой группы...',
    enterTitleObjectText = 'Имя нового объекта...',
    enterNewTitleProgramText = 'Введите новое название проекта...',
    enterNewTitleResourceText = 'Введите новое название ресурса...',
    enterNewTitleSceneText = 'Введите новое название группы...',
    enterNewTitleObjectText = 'Введите новое имя объекта...',
    chooseAction = 'Выберите действие',
    remove = 'Удалить',
    copy = 'Копировать',
    export = 'Экспортировать',
    exportApk = 'Экспортировать в apk',
    rename = 'Переименовать',
    editScene = 'Редактировать группу',
    textures = 'Текстуры',
    ucomment = 'Разморозить',
    comment = 'Заморозить',
    documentation = 'Информация про блок',
  },
  ['en'] = {
    blocks = {
      -- event
      ['onStart'] = {'At start'},
      ['onClick'] = {'When a finger touches an object'},
      ['onClickEnd'] = {'When the finger releases the object'},
      ['onClickMove'] = {'When your finger is on the screen', {'Offset (X):', 'Offset (Y):'}},
      ['onFun'] = {'When will the function be received', {'Function name:'}},
      ['onCollisionStart'] = {'When the collision occurs'},
      ['onCollisionEnd'] = {'When the collision is over'},
      ['onBack'] = {'When you click on the "Back" button'},
      ['onHide'] = {'The application was hidden from the screen'},
      ['onView'] = {'The application was shown on the screen'},

      -- data
      ['setVar'] = {'Set variable value', {'Variable name:', 'Value:'}},
      ['updVar'] = {'Add value to variable', {'Variable name:', 'Value:'}},
      ['setShowText'] = {'Show text on screen', {'Variable name:', 'Font:', 'Align:', 'Size:', 'Width:', 'Height:'}},
      ['setHideText'] = {'Hide text from screen', {'Variable name:'}},
      ['updTable'] = {'Overwrite table', {'Table name:', 'Value:'}},
      ['setPosText'] = {'Set text position', {'Variable name:', 'Value (X):', 'Value (Y)'}},
      ['setPosXText'] = {'Set text position X', {'Variable name:', 'Value (X):'}},
      ['setPosYText'] = {'Set text position Y', {'Variable name:', 'Value (Y):'}},
      ['setRotationText'] = {'Set text rotation', {'Variable name:', 'Value (0-360):'}},
      ['setAlignText'] = {'Set text align', {'Variable name:', 'Align:'}},
      ['setAlphaText'] = {'Set text transparency', {'Variable name:', 'Value (0-100):'}},
      ['setColorText'] = {'Set text color', {'Variable name:', 'Color:'}},
      ['setRGBColorText'] = {'Set rgb text color', {'Variable name:', 'Value r (0-255):', 'Value g (0-255):', 'Value b (0-255):'}},
      ['setHEXColorText'] = {'Set hex text color', {'Variable name:', 'Value hex:'}},
      ['updColorText'] = {'Change text color', {'Variable name:', 'Value (0-255):'}},
      ['updRColorText'] = {'Change text red color', {'Variable name:', 'Value (0-255):'}},
      ['updGColorText'] = {'Change text green color', {'Variable name:', 'Value (0-255):'}},
      ['updBColorText'] = {'Change text blue color', {'Variable name:', 'Value (0-255):'}},
      ['setFrontText'] = {'Place text on layer above', {'Variable name:'}},
      ['setBackText'] = {'Place text on layer below', {'Variable name:'}},
      ['readVar'] = {'Read variable', {'Variable name:'}},
      ['writeVar'] = {'Write variable', {'Variable name:'}},
      ['setTable'] = {'Set item to table (1)', {'Table name:', 'Key (1):', 'Value:'}},
      ['setTable2'] = {'Set item to table (2)', {'Table name:', 'Key (1):', 'Key (2):', 'Value:'}},
      ['setTable3'] = {'Set item to table (3)', {'Table name:', 'Key (1):', 'Key (2):', 'Key (3):', 'Value:'}},
      ['setTable4'] = {'Set item to table (4)', {'Table name:', 'Key (1):', 'Key (2):', 'Key (3):', 'Key (4):', 'Value:'}},
      ['removeTable'] = {'Remove item from table (1)', {'Table name:', 'Key (1):'}},
      ['removeTable2'] = {'Remove item from table (2)', {'Table name:', 'Key (1):', 'Key (2):'}},
      ['removeTable3'] = {'Remove item from table (3)', {'Table name:', 'Key (1):', 'Key (2):', 'Key (3):'}},
      ['removeTable4'] = {'Remove item from table (4)', {'Table name:', 'Key (1):', 'Key (2):', 'Key (3):', 'Key (4):'}},

      -- object
      ['setPos'] = {'Set position', {'Value (X):', 'Value (Y):'}},
      ['setX'] = {'Set position X', {'Value (X):'}},
      ['setY'] = {'Set position Y', {'Value (Y):'}},
      ['setSize'] = {'Set size', {'Value (%):'}},
      ['setWidth'] = {'Set width', {'Value:'}},
      ['setHeight'] = {'Set height', {'Value:'}},
      ['updX'] = {'Change position X', {'Value (X):'}},
      ['updY'] = {'Change position Y', {'Value (Y):'}},
      ['updSize'] = {'Change size', {'Value (%):'}},
      ['updWidth'] = {'Change width', {'Value:'}},
      ['updHeight'] = {'Change height', {'Value:'}},
      ['setHide'] = {'Hide object from screen'},
      ['setView'] = {'Show object on screen'},
      ['setRotation'] = {'Set rotation', {'Value (0-360):'}},
      ['setAlpha'] = {'Set transparency', {'Value (0-100):'}},
      ['setTag'] = {'Assign to tag', {'Tag name:'}},
      ['setFront'] = {'Place on layer above'},
      ['setBack'] = {'Place on layer below'},
      ['setNameTexture'] = {'Set texture from name', {'Texture name:'}},
      ['setIndexTexture'] = {'Set texture from index', {'Texture index:'}},
      ['setLinkTexture'] = {'Set texture from link', {'Value (Link):'}},
      ['resetSize'] = {'Set size to texture'},

      -- control
      ['fun'] = {'Call a function', {'Function name:'}},
      ['funParams'] = {'Call a function with parameters', {'Function name:', 'Table name:'}},
      ['useTag'] = {'Use blocks for tag', {'Tag name:'}},
      ['useTagEnd'] = {'End of tag use'},
      ['if'] = {'If the condition is true', {'Condition:'}},
      ['ifElse'] = {'If the condition is true, Otherwise', {'Condition:'}},
      ['else'] = {'Otherwise'},
      ['ifEnd'] = {'End of condition'},
      ['ifElseEnd'] = {'End of condition'},
      ['for'] = {'Repeat N times', {'Number of repetitions (N):'}},
      ['forEnd'] = {'End of repeat'},
      ['enterFrame'] = {'Repeat forever'},
      ['enterFrameEnd'] = {'End of eternity'},
      ['timer'] = {'Timer', {'Value (Seconds):'}},
      ['groupCreate'] = {'Create group', {'Group name:'}},
      ['groupView'] = {'View group', {'Group name:'}},
      ['setColorBackground'] = {'Set background color', {'Color:'}},
      ['setRGBColorBackground'] = {'Set rgb background color', {'Value r (0-255):', 'Value g (0-255):', 'Value b (0-255):'}},
      ['setHEXColorBackground'] = {'Set hex background color', {'Value hex:'}},
      ['fileLine'] = {'Read file line by line', {'Variable name:', 'The path to the file:', 'Catalog:'}},
      ['fileLineEnd'] = {'End of reading the file'},
      ['fileRead'] = {'Read file', {'Variable name:', 'The path to the file:', 'Catalog:'}},
      ['fileWrite'] = {'Overwrite file', {'Value:', 'The path to the file:', 'Catalog:'}},
      ['fileUpdate'] = {'Write to the end of the file', {'Value:', 'The path to the file:', 'Catalog:'}},
      ['fileMove'] = {'Move/rename file', {'The path to the file (1):', 'Catalog (1):', 'The path to the file (2):', 'Catalog (2):'}},
      ['fileCopy'] = {'Copy file', {'The path to the file (1):', 'Catalog (1):', 'The path to the file (2):', 'Catalog (2):'}},
      ['fileRemove'] = {'Delete file', {'The path to the file:', 'Catalog:'}},
      ['onMultitouch'] = {'Activate multitouch'},
      ['offMultitouch'] = {'Deactivate multitouch'},
      ['closeApp'] = {'Close application'},
      ['commentYourself'] = {'Comment (for yourself)', {'Comment:'}},

      -- controlother
      ['inputText'] = {'Get text from user', {'User text:', 'Variable name:'}},
      ['createTextField'] = {'Create one line text field', {'Text field:', 'User text:', 'Color:', 'Size:', 'Field background:', 'Font:'}},
      ['createTextBox'] = {'Create multiline text field', {'Text field:', 'User text:', 'Color:', 'Size:', 'Field background:', 'Font:'}},
      ['removeTextField'] = {'Delete text field', {'Text field:'}},
      ['getTextField'] = {'Get text', {'Text field:', 'Variable name:'}},
      ['setTextField'] = {'Set text', {'Text field:', 'Value (Text):'}},
      ['getOldTextField'] = {'Get old text', {'Text field:', 'Variable name:'}},
      ['setPosField'] = {'Set the position of the text field', {'Text field:', 'Value (X):', 'Value (Y):'}},
      ['setSizeField'] = {'Set the dimensions of the text field', {'Text field:', 'Value (Width):', 'Value (Height):'}},
      ['setHideField'] = {'Hide text field', {'Text field:'}},
      ['setViewField'] = {'Show text field', {'Text field:'}},
      ['setInputTypeField'] = {'Set input type', {'Text field:', 'Input type:'}},
      ['setEditField'] = {'Permission to edit', {'Text field:', 'Permission:'}},
      ['closeKeyboard'] = {'Turn off the onscreen keyboard'},

      -- physics
      ['setBody'] = {'Add physical body', {'Type:', 'Density:', 'Bounce:', 'Friction:'}},
      ['removeBody'] = {'Remove physical body'},
      ['setNewBody'] = {'Set type', {'Type:'}},
      ['setHitboxMesh'] = {'Set hitbox (mesh)', {'Coarseness texels:'}},
      ['setHitboxBox'] = {'Set hitbox (structure)', {'Hitbox:'}},
      ['setHitboxCircle'] = {'Set hitbox (circle)', {'Value (Radius):'}},
      ['setGravity'] = {'Set gravity', {'Value (Gravity):'}},
      ['setLinearVelocity'] = {'Jump', {'Value (X):', 'Value (Y):'}},
      ['setLinearVelocityX'] = {'Jump X', {'Value (X):'}},
      ['setLinearVelocityY'] = {'Jump Y', {'Value (Y):'}},
      ['setSensor'] = {'Set sensor mode'},
      ['setNotSensor'] = {'Delete sensor mode'},
      ['setFixedRotation'] = {'Make the body non-rotatable'},
      ['setNotFixedRotation'] = {'Make the body rotate'},
      ['setWorldGravity'] = {'Set world gravity', {'Value (X):', 'Value (Y):'}},
      ['setVisiblePhysics'] = {'View hitboxes'},
      ['setNotVisiblePhysics'] = {'Hide hitboxes'},
      ['setBullet'] = {'Set bullet property'},
      ['setNotBullet'] = {'Remove bullet property'},
      ['setAwake'] = {'To wake'},
      ['setAngularVelocity'] = {'Set angular velocity', {'Value:'}},
      ['setAngularDamping'] = {'Set angular damping', {'Value:'}},
      ['setLinearDamping'] = {'Set linear damping', {'Value:'}},
      ['setForce'] = {'Apply force', {'Value (X):', 'Value (Y):'}},
      ['setLinearImpulse'] = {'Apply linear impulse', {'Value (X):', 'Value (Y):'}},
      ['setTorque'] = {'Apply torque', {'Value:'}},
      ['setAngularImpulse'] = {'Apply angular impulse', {'Value:'}},
      ['setPowerPhysics'] = {'Set physics power', {'Computing power:'}},
      ['startPhysics'] = {'Enable physics'},
      ['stopPhysics'] = {'Disable physics'},

      -- network
      ['openUrl'] = {'Open link in browser', {'Value (Link):'}},
      ['setGet'] = {'GET request', {'Value (Link):', 'Variable name:'}},
      ['setPost'] = {'POST request', {'Value (Link):', 'Body:', 'Variable name:', 'Headers:'}}
    },
    editorList = {
      fun = {
        -- {'decode_json', 'decode_json'},
        {'radical', 'radical'},
        {'random', 'random'},
        {'round', 'round'},
        {'remainder', '%'},
        {'sinus', 'sin'},
        {'cosinus', 'cos'},
        {'tangent', 'tan'},
        {'cotangent', 'ctan'},
        {'arcsinus', 'arcsin'},
        {'arccosinus', 'arccos'},
        {'arctangent', 'arctan'},
        {'arccotangent', 'arcctan'},
        {'natural_logarithm', 'log'},
        {'decimal_logarithm', 'log10'},
        {'pi', 'pi'},
        {'unix_time', 'unix_time'},
      },
      prop = {
        {'positionX', 'posX'},
        {'positionY', 'posY'},
        {'positionZ', 'posZ'},
        {'width', 'width'},
        {'height', 'height'},
        {'rotation', 'rotation'},
        {'tag', 'tag'},
      },
      log = {
        {'true', 'true'},
        {'false', 'false'},
        {'=', '='},
        {'>', '>'},
        {'<', '<'},
        {'>=', '>='},
        {'<=', '<='},
        {'~=', '~='},
        {'and', 'and'},
        {'or', 'or'},
        {'not', 'not'},
      },
    },
    offMagnetX = 'Turn off magnet on X',
    offMagnetY = 'Turn off magnet on Y',
    onMagnetX = 'Turn on magnet on X',
    onMagnetY = 'Turn on magnet on Y',
    saveAndExit = 'Save hitbox and exit',
    index = 'Index: ',
    indexBox = 'Structure index',
    viewIndexBox = 'View structure index',
    viewLines = 'View lines',
    hideLines = 'Hide lines',
    onPhysics = 'Enable physics',
    viewHitbox = 'View hitbox',
    hideHitbox = 'Hide hitbox',
    addBox = 'Add structure',
    removeBox = 'Delete structure',
    addPoint = 'Add point',
    removePoint = 'Delete point',
    shapephyscircle = 'Circle',
    shapephysbox = 'Structures',
    shapephysmesh = 'Mesh',
    editfieldtrue = 'Can edit',
    editfieldfalse = 'Can\'t edit',
    typefielddefault = 'Default',
    typefieldnumber = 'Number',
    typefielddecimal = 'Decimal',
    typefieldphone = 'Phone number',
    typefieldurl = 'Link',
    typefieldemail = 'Email',
    typefieldnoemoji = 'No emoji',
    bgfieldtrue = 'Leave',
    bgfieldfalse = 'Remove',
    resourcesTitle = 'Resources',
    resource = 'Manage resources',
    leftAlign = 'Left',
    centerAlign = 'Center',
    rightAlign = 'Right',
    inputHexTitle = 'Enter hex',
    inputHexText = 'Enter hex (e.g. #FFFFFF)',
    red = 'Red:',
    green = 'Green:',
    blue = 'Blue:',
    isNotPhyRotation = 'Not rotatable',
    isPhyRotation = 'Rotatable',
    isSensor = 'Not visible',
    isNotSensor = 'Visible',
    staticBody = 'Static',
    dynamicBody = 'Dinamic',
    currentCopy = 'Current',
    lastCopy = 'Last',
    allCopy = 'All',
    selfCopy = 'Self',
    newfieldTitle = 'Name the text field',
    newfieldText = 'Write a name for the new text field',
    newfield = 'Create text field',
    newtagTitle = 'Name the tag',
    newtagText = 'Write a name for the new tag',
    newtag = 'Create tag',
    newfuncTitle = 'Name the function',
    newfuncText = 'Write a name for the new function',
    newfunc = 'Create function',
    newtablTitle = 'Name the table',
    newtablText = 'Write a name for the new table',
    newtabl = 'Create table',
    newvariableTitle = 'Name the variable',
    newvariableText = 'Write a name for the new variable',
    newvariable = 'Create variable',
    editorVar = 'Variables',
    editorTable = 'Tables',
    editorFun = 'Functions',
    editorProp = 'Properties',
    editorLog = 'Logics',
    editorObj = 'Objects',
    editorDevice = 'Device',
    editorLocalTable = 'local',
    editorInputLocal = 'Local',
    editorInputText = 'Text',
    editorTitle = 'Expression editor',
    typeevent = 'Events',
    typedata = 'Data',
    typeobject = 'Objects',
    -- typecopy = 'Copies',
    typecontrol = 'Control',
    typecontrolother = 'Other',
    typephysics = 'Physics',
    -- typephysicscopy = 'Physics (Copies)',
    typenetwork = 'Network',
    typenot = 'Something will',
    newblocksTitle = 'New block',
    blocksTitle = 'Blocks',
    close = 'Close',
    errorPermissionText = 'If Construct Code did not automatically request access to the repository, then please do it manually in the settings of your phone, nice development',
    errorPermissionTitle = 'Access error',
    noTexture = 'No texture',
    firstScene = 'Main group',
    changeTexture = 'Change texture',
    texturesTitle = 'Textures',
    enterTitleTextureText = 'Name a new texture...',
    enterNewTitleTextureText = 'Enter a new texture name...',
    myProgramText = 'My programs',
    continueText = 'Continue',
    settingsText = 'Settings',
    buttonInput = 'Ok',
    settingsTitle = 'Settings',
    settingsStdImport = 'Standard image import',
    settingsPictureView = 'Show illustrations',
    settingsLanguage = 'Application language',
    social = 'Social networks',
    socialText = 'Go to the official groups/channels of the program',
    vk = 'Vkontakte',
    tg = 'Telegram',
    objectsTitle = 'Objects',
    scenesTitle = 'Groups',
    programsTitle = 'My programs',
    chooseOrientation = 'Choose orientation',
    chooseOrientationText = 'Choose an orientation for a new project\nPortrait: 720x1280\nLandscape: 1280x720',
    portrait = 'Portrait',
    landscape = 'Landscape',
    whichObject = 'What object to create?',
    chooseTypeObject = 'Choose what type of object you want to create',
    noPixelImage = 'Not pixel picture',
    pixelImage = 'Pixel picture',
    enterTextDescription = 'Enter the text you want to add',
    enterText = 'Enter text',
    enterName = 'Enter name',
    enterTitle = 'Enter title',
    enterTitleProgramText = 'New project name...',
    enterTitleResourceText = 'New resource name...',
    enterTitleSceneText = 'New group name...',
    enterTitleObjectText = 'New object name...',
    enterNewTitleProgramText = 'Enter a new project name...',
    enterNewTitleResourceText = 'Enter a new resource name...',
    enterNewTitleSceneText = 'Enter a new group name...',
    enterNewTitleObjectText = 'Enter a new object name...',
    chooseAction = 'Choose action',
    remove = 'Remove',
    copy = 'Copy',
    export = 'Export',
    exportApk = 'Export to apk',
    rename = 'Rename',
    editScene = 'Edit group',
    textures = 'Texrures',
    ucomment = 'Uncomment',
    comment = 'Comment',
    documentation = 'Block information',
  },
}
