stringsLanguage = {
  langs = {
    {'ru', 'Русский'},
    {'en', 'English'},
    -- {'in', 'हिन्दी'},
    -- {'cn', '中文'},
    -- {'es', 'Español'},
  },
  ['ru'] = {
    blocks = {
      -- event
      ['onStart'] = {'При старте'},
      ['onClick'] = {'Когда палец прикасается к объекту'},
      ['onClickEnd'] = {'Когда палец отпускает объект'},
      ['onFun'] = {'Когда будет получена функция', {'Название функции:'}},
      ['onBack'] = {'При нажатии на кнопку "Назад"'},
      ['onHide'] = {'Приложение свернули с главного экрана'},
      ['onView'] = {'Приложение вернули на главный экран'},

      -- data
      ['setVar'] = {'Установить значение переменной', {'Название переменной:', 'Значение:'}},
      ['updVar'] = {'Добавить значение к переменной', {'Название переменной:', 'Значение:'}},
      ['setShowText'] = {'Показать текст на экране', {'Название переменной:', 'Шрифт:', 'Цвет:', 'Размер:'}},
      ['setHideText'] = {'Скрыть текст с экрана', {'Название переменной:'}},
      ['setTable'] = {'Добавить элемент в таблицу', {'Название таблицы:', 'Ключ:', 'Значение:'}},

      -- object
      ['setPos'] = {'Установить позицию', {'Значение (X):', 'Значение (Y):'}},
      ['setX'] = {'Установить позицию X', {'Значение (X):'}},
      ['setY'] = {'Установить позицию Y', {'Значение (Y):'}},
      ['setSize'] = {'Установить размер', {'Значение (%):'}},

      -- copy
      ['setCopy'] = {'Копировать', {'Кого:'}},
      ['removeCopy'] = {'Удалить копию', {'Копия:'}},
      ['setPosCopy'] = {'Установить позицию копии', {'Копия:', 'Значение (X):', 'Значение (Y):'}},

      -- control
      ['if'] = {'Если условие истина', {'Условие:'}},
      ['ifEnd'] = {'Конец условия'},
      ['for'] = {'Повторить N раз', {'Количество повторов (N):'}},
      ['forEnd'] = {'Конец цикла'},
      ['timer'] = {'Таймер', {'Значение (Секунды):'}},
      ['fileLine'] = {'Прочитать файл по строкам', {'Название переменной:', 'Путь к файлу:', 'Каталог:'}},
      ['fileLineEnd'] = {'Конец прочтения файла'},
      ['fileRead'] = {'Прочитать файл', {'Название переменной:', 'Путь к файлу:', 'Каталог:'}},
      ['fileWrite'] = {'Перезаписать файл', {'Значение:', 'Путь к файлу:', 'Каталог:'}},
      ['fileUpdate'] = {'Записать в конец файла', {'Значение:', 'Путь к файлу:', 'Каталог:'}},
      ['fileMove'] = {'Переместить/переименовать файл', {'Путь к файлу (1):', 'Каталог (1):', 'Путь к файлу (2):', 'Каталог (2):'}},
      ['fileCopy'] = {'Копировать файл', {'Путь к файлу (1):', 'Каталог (1):', 'Путь к файлу (2):', 'Каталог (2):'}},
      ['fileRemove'] = {'Удалить файл', {'Путь к файлу:', 'Каталог:'}},

      -- physics
      ['setBody'] = {'Добавить физическое тело', {'Физ. тело:', 'Плотность:', 'Прыгучесть:', 'Трение:'}},
      ['removeBody'] = {'Удалить физическое тело'},
      ['startPhysics'] = {'Включить физику'},
      ['stopPhysics'] = {'Выключить физику'},

      -- physicscopy
      ['setGravityCopy'] = {'Установить гравитацию копии', {'Копия:', 'Значение (Гравитация):'}},
      ['setSensorCopy'] = {'Тип невидимости физ. тела копии', {'Копия:', 'Значение:'}},
      ['setPhyRotationCopy'] = {'Тип вращения физ. тела копии', {'Копия:', 'Значение:'}},

      -- network
      ['openUrl'] = {'Открыть ссылку в браузере', {'Значение (Ссылка):'}},
      ['setGet'] = {'GET запрос', {'Название переменной:', 'Значение (Ссылка):'}},
      ['setPost'] = {'POST запрос', {'Название таблицы:', 'Название переменной:', 'Значение (Ссылка):'}}
    },
    editorList = {
      table = {
        {'[', '['},
        {']', ']'},
      },
      fun = {
        {'синус', 'sin'},
        {'косинус', 'cos'},
        {'тангенс', 'tan'},
        {'котангенс', 'ctan'},
        {'арксинус', 'arcsin'},
        {'арккосинус', 'arccos'},
        {'арктангенс', 'arctan'},
        {'арккотангенс', 'arcctan'},
        {'логарифм', 'log'},
        {'pi', 'pi'},
        {'корень', 'radical'},
        {'рандом', 'random'},
        {'округлить', 'round'},
        {'остаток', '%'},
      },
      prop = {
        {'позицияX', 'posX'},
        {'позицияY', 'posY'},
        {'ширина', 'width'},
        {'высота', 'height'},
        {'угол', 'rotation'},
        {'тег', 'tag'},
      },
      log = {
        {'истина', 'true'},
        {'ложь', 'false'},
        {'=', '='},
        {'>', '>'},
        {'<', '<'},
        {'>=', '>='},
        {'<=', '<='},
        {'~=', '~='},
        {'и', 'and'},
        {'или', 'or'},
        {'не', 'not'},
      },
    },
    editorVar = 'Переменные',
    editorTable = 'Таблицы',
    editorFun = 'Функции',
    editorProp = 'Свойства',
    editorLog = 'Логика',
    editorObj = 'Объекты',
    editorDevice = 'Устройство',
    editorLocalTable = 'локал',
    editorInputLocal = 'Локал',
    editorInputText = 'Текст',
    editorTitle = 'Редактор выражений',
    typeevent = 'События',
    typedata = 'Данные',
    typeobject = 'Объекты',
    typecopy = 'Копии',
    typecontrol = 'Управление',
    typephysics = 'Физика (Объекты)',
    typephysicscopy = 'Физика (Копии)',
    typenetwork = 'Интернет',
    typenot1 = 'Что-то будет',
    typenot2 = 'Что-то будет',
    typenot3 = 'Что-то будет',
    typenot4 = 'Что-то будет',
    newblocksTitle = 'Новый блок',
    blocksTitle = 'Блоки',
    close = 'Закрыть',
    errorPermissionText = 'Если Construct Code автоматически не запросил доступ к хранилищу, то сделайте это пожалуйста вручную в настройках вашего телефона, приятной разработки',
    errorPermissionTitle = 'Ошибка доступа',
    noTexture = 'Без текстуры',
    firstScene = 'Основная группа',
    changeTexture = 'Сменить текстуру',
    texturesTitle = 'Текстуры',
    enterTitleTextureText = 'Имя новой текстуры...',
    enterNewTitleTextureText = 'Введите новое имя текстуры...',
    myProgramText = 'Мои программы',
    continueText = 'Продолжить',
    settingsText = 'Настройки',
    buttonInput = 'Ок',
    settingsTitle = 'Настройки',
    settingsStdImport = 'Стандартный импорт картинок',
    settingsPictureView = 'Показывать иллюстрации',
    settingsLanguage = 'Язык приложения',
    social = 'Социальные сети',
    socialText = 'Перейти в оффициальные группы/каналы программы',
    vk = 'Вконтакте',
    tg = 'Телеграм',
    objectsTitle = 'Объекты',
    scenesTitle = 'Группы',
    programsTitle = 'Мои программы',
    chooseOrientation = 'Выберите ориентацию',
    chooseOrientationText = 'Выберите ориентацию для нового проекта\nПортретный: 720x1280\nЛандшафтный: 1280x720',
    portrait = 'Портретный',
    landscape = 'Ландшафтный',
    whichObject = 'Какой объект создать?',
    chooseTypeObject = 'Выберите, какой тип объекта вы хотите создать',
    noPixelImage = 'Не пиксельную картинку',
    pixelImage = 'Пиксельную картинку',
    enterTextDescription = 'Введите текст, который хотите добавить',
    enterText = 'Введите текст',
    enterName = 'Введите имя',
    enterTitle = 'Введите название',
    enterTitleProgramText = 'Название нового проекта...',
    enterTitleSceneText = 'Название новой группы...',
    enterTitleObjectText = 'Имя нового объекта...',
    enterNewTitleProgramText = 'Введите новое название проекта...',
    enterNewTitleSceneText = 'Введите новое название группы...',
    enterNewTitleObjectText = 'Введите новое имя объекта...',
    chooseAction = 'Выберите действие',
    remove = 'Удалить',
    copy = 'Копировать',
    export = 'Экспортировать',
    exportApk = 'Экспортировать в apk',
    rename = 'Переименовать',
    editScene = 'Редактировать группу',
    textures = 'Текстуры',
    comment = 'Заморозить',
    documentation = 'Информация про блок',
  },
  ['en'] = {
    blocks = {
      -- event
      ['onStart'] = {'At start'},
      ['onClick'] = {'When a finger touches an object'},
      ['onClickEnd'] = {'When the finger releases the object'},
      ['onFun'] = {'When will the function be received', {'Function name:'}},
      ['onBack'] = {'When you click on the "Back" button'},
      ['onHide'] = {'The application was hidden from the screen'},
      ['onView'] = {'The application was shown on the screen'},

      -- data
      ['setVar'] = {'Set variable value', {'Variable name:', 'Value:'}},
      ['updVar'] = {'Add value to variable', {'Variable name:', 'Value:'}},
      ['setShowText'] = {'Show text on screen', {'Variable name:', 'Font:', 'Color:', 'Size:'}},
      ['setHideText'] = {'Hide text from screen', {'Variable name:'}},
      ['setTable'] = {'Add item to table', {'Table name:', 'Key:', 'Value:'}},

      -- object
      ['setPos'] = {'Set position', {'Value (X):', 'Value (Y):'}},
      ['setX'] = {'Set position X', {'Value (X):'}},
      ['setY'] = {'Set position Y', {'Value (Y):'}},
      ['setSize'] = {'Set size', {'Value (%):'}},

      -- copy
      ['setCopy'] = {'Copy', {'Whom:'}},
      ['removeCopy'] = {'Delete copy', {'Copy:'}},
      ['setPosCopy'] = {'Set copy position', {'Copy:', 'Value (X):', 'Value (Y):'}},

      -- control
      ['if'] = {'If the condition is true', {'Condition:'}},
      ['ifEnd'] = {'End of condition'},
      ['for'] = {'Repeat N times', {'Number of repetitions (N):'}},
      ['forEnd'] = {'End of repeat'},
      ['timer'] = {'Timer', {'Value (Seconds):'}},
      ['fileLine'] = {'Read file line by line', {'Variable name:', 'The path to the file:', 'Catalog:'}},
      ['fileLineEnd'] = {'End of reading the file'},
      ['fileRead'] = {'Read file', {'Variable name:', 'The path to the file:', 'Catalog:'}},
      ['fileWrite'] = {'Overwrite file', {'Value:', 'The path to the file:', 'Catalog:'}},
      ['fileUpdate'] = {'Write to the end of the file', {'Value:', 'The path to the file:', 'Catalog:'}},
      ['fileMove'] = {'Move/rename file', {'The path to the file (1):', 'Catalog (1):', 'The path to the file (2):', 'Catalog (2):'}},
      ['fileCopy'] = {'Copy file', {'The path to the file (1):', 'Catalog (1):', 'The path to the file (2):', 'Catalog (2):'}},
      ['fileRemove'] = {'Delete file', {'The path to the file:', 'Catalog:'}},

      -- physics
      ['setBody'] = {'Add physical body', {'Phys. body:', 'Density:', 'Bounce:', 'Friction:'}},
      ['removeBody'] = {'Remove physical body'},
      ['startPhysics'] = {'Enable physics'},
      ['stopPhysics'] = {'Disable physics'},

      -- physicscopy
      ['setGravityCopy'] = {'Set copy gravity', {'Copy:', 'Value (Gravity):'}},
      ['setSensorCopy'] = {'Physical invisibility type body copy', {'Copy:', 'Value:'}},
      ['setPhyRotationCopy'] = {'Rotation type nat. body copy', {'Copy:', 'Value:'}},

      -- network
      ['openUrl'] = {'Open link in browser', {'Value (Link):'}},
      ['setGet'] = {'GET request', {'Variable name:', 'Value (Link):'}},
      ['setPost'] = {'POST request', {'Table name:', 'Variable name:', 'Value (Link):'}}
    },
    editorList = {
      table = {
        {'[', '['},
        {']', ']'},
      },
      fun = {
        {'sinus', 'sin'},
        {'cosinus', 'cos'},
        {'tangent', 'tan'},
        {'cotangent', 'ctan'},
        {'arcsinus', 'arcsin'},
        {'arccosinus', 'arccos'},
        {'arctangent', 'arctan'},
        {'arccotangent', 'arcctan'},
        {'logarithm', 'log'},
        {'pi', 'pi'},
        {'radical', 'radical'},
        {'random', 'random'},
        {'round', 'round'},
        {'remainder', '%'},
      },
      prop = {
        {'positionX', 'posX'},
        {'positionY', 'posY'},
        {'width', 'width'},
        {'height', 'height'},
        {'rotation', 'rotation'},
        {'tag', 'tag'},
      },
      log = {
        {'true', 'true'},
        {'false', 'false'},
        {'=', '='},
        {'>', '>'},
        {'<', '<'},
        {'>=', '>='},
        {'<=', '<='},
        {'~=', '~='},
        {'and', 'and'},
        {'or', 'or'},
        {'not', 'not'},
      },
    },
    editorVar = 'Variables',
    editorTable = 'Tables',
    editorFun = 'Functions',
    editorProp = 'Properties',
    editorLog = 'Logics',
    editorObj = 'Objects',
    editorDevice = 'Device',
    editorLocalTable = 'local',
    editorInputLocal = 'Local',
    editorInputText = 'Text',
    editorTitle = 'Expression editor',
    typeevent = 'Events',
    typedata = 'Data',
    typeobject = 'Objects',
    typecopy = 'Copies',
    typecontrol = 'Control',
    typephysics = 'Physics (Objects)',
    typephysicscopy = 'Physics (Copies)',
    typenetwork = 'Network',
    typenot1 = 'Something will',
    typenot2 = 'Something will',
    typenot3 = 'Something will',
    typenot4 = 'Something will',
    newblocksTitle = 'New block',
    blocksTitle = 'Blocks',
    close = 'Close',
    errorPermissionText = 'If Construct Code did not automatically request access to the repository, then please do it manually in the settings of your phone, nice development',
    errorPermissionTitle = 'Access error',
    noTexture = 'No texture',
    firstScene = 'Main group',
    changeTexture = 'Change texture',
    texturesTitle = 'Textures',
    enterTitleTextureText = 'Name a new texture...',
    enterNewTitleTextureText = 'Enter a new texture name...',
    myProgramText = 'My programs',
    continueText = 'Continue',
    settingsText = 'Settings',
    buttonInput = 'Ok',
    settingsTitle = 'Settings',
    settingsStdImport = 'Standard image import',
    settingsPictureView = 'Show illustrations',
    settingsLanguage = 'Application language',
    social = 'Social networks',
    socialText = 'Go to the official groups/channels of the program',
    vk = 'Vkontakte',
    tg = 'Telegram',
    objectsTitle = 'Objects',
    scenesTitle = 'Groups',
    programsTitle = 'My programs',
    chooseOrientation = 'Choose orientation',
    chooseOrientationText = 'Choose an orientation for a new project\nPortrait: 720x1280\nLandscape: 1280x720',
    portrait = 'Portrait',
    landscape = 'Landscape',
    whichObject = 'What object to create?',
    chooseTypeObject = 'Choose what type of object you want to create',
    noPixelImage = 'Not pixel picture',
    pixelImage = 'Pixel picture',
    enterTextDescription = 'Enter the text you want to add',
    enterText = 'Enter text',
    enterName = 'Enter name',
    enterTitle = 'Enter title',
    enterTitleProgramText = 'New project name...',
    enterTitleSceneText = 'New group name...',
    enterTitleObjectText = 'New object name...',
    enterNewTitleProgramText = 'Enter a new project name...',
    enterNewTitleSceneText = 'Enter a new group name...',
    enterNewTitleObjectText = 'Enter a new object name...',
    chooseAction = 'Choose action',
    remove = 'Remove',
    copy = 'Copy',
    export = 'Export',
    exportApk = 'Export to apk',
    rename = 'Rename',
    editScene = 'Edit group',
    textures = 'Texrures',
    comment = 'Comment',
    documentation = 'Block information',
  },
}
